unit module Lling::Llang::GeneratedAbi;

use NativeCall;
need Vinary::Tree::Interop;

# Code generated by scripts/generate-raku-abi.py from bindings/api.json
# after validating include/lling_llang.h and the provider shim; DO NOT EDIT.
our constant ABI-VERSION is export(:abi) = 1;
our constant API-REVISION is export(:abi) = 6;
our constant TYPED-ABI-VERSION is export(:abi) = 2;
our constant PROVIDER-ABI-VERSION is export(:abi) = 1;
our constant PROVIDER-API-REVISION is export(:abi) = 3;
our constant DESCRIPTOR-SIGNATURE-KNOWN is export(:abi) = 1 +< 0;
our constant DESCRIPTOR-SNAPSHOT-PRESENT is export(:abi) = 1 +< 1;
our constant DESCRIPTOR-CONTEXT-PRESENT is export(:abi) = 1 +< 2;
our constant BUDGET-STATES is export(:abi) = 1 +< 0;
our constant BUDGET-ARCS is export(:abi) = 1 +< 1;
our constant BUDGET-BYTES is export(:abi) = 1 +< 2;
our constant BUDGET-WORK is export(:abi) = 1 +< 3;
our constant PROVIDER-CAPABILITY-WFST-PROVIDER is export(:abi) = 1;
our constant PROVIDER-CAPABILITY-SEMIRING-BASE is export(:abi) = 2;
our constant PROVIDER-CAPABILITY-SEMIRING-OPTIONAL is export(:abi) = 4;
our constant PROVIDER-CAPABILITY-SEMIRING-BATCH is export(:abi) = 8;
our constant PROVIDER-CAPABILITY-SEMIRING-PROPERTIES is export(:abi) = 16;

our enum Status is export(:abi) (
    OK => 0,
    INVALID-ARGUMENT => 1,
    NULL-POINTER => 2,
    PANIC => 3,
    INCOMPATIBLE-RESOURCE => 4,
    PROVIDER-ERROR => 5,
    LIMIT-EXCEEDED => 6,
    CLOSED => 7,
);

our enum PrecisionV2 is export(:abi) (
    PRECISION-EXACT => 1,
    PRECISION-APPROXIMATE => 2,
    PRECISION-UNKNOWN => 3,
);

our enum CompletenessV2 is export(:abi) (
    COMPLETENESS-COMPLETE => 1,
    COMPLETENESS-INCOMPLETE => 2,
);

our enum ApplicabilityV2 is export(:abi) (
    APPLICABILITY-APPLICABLE => 1,
    APPLICABILITY-UNSUPPORTED => 2,
    APPLICABILITY-UNKNOWN => 3,
);

our enum TerminationV2 is export(:abi) (
    TERMINATION-SUCCEEDED => 1,
    TERMINATION-CANCELLED => 2,
    TERMINATION-BUDGET-EXHAUSTED => 3,
    TERMINATION-FAILED => 4,
);

our enum EvidenceStateV2 is export(:abi) (
    EVIDENCE-NONE => 0,
    EVIDENCE-CANDIDATE => 1,
    EVIDENCE-VERIFIED => 2,
    EVIDENCE-STALE => 3,
    EVIDENCE-INVALID => 4,
);

our enum CancellationReasonV2 is export(:abi) (
    REQUESTED => 1,
    DEADLINE => 2,
    BUDGET => 3,
    SOURCE => 4,
);

our class AbiV2Header is repr('CStruct') is export(:abi) {
    has uint32 $.struct-size is rw;
    has uint32 $.abi-version is rw;
    has uint64 $.flags is rw;
    has uint64 $.reserved is rw;
    multi method new(
        UInt:D :$struct-size!, UInt:D :$flags = 0
        --> AbiV2Header:D
    ) {
        self.bless(:$struct-size, abi-version => TYPED-ABI-VERSION,
            :$flags, reserved => 0)
    }
}

our class BudgetV2 is repr('CStruct') is export(:abi) {
    HAS AbiV2Header $.header is rw;
    has uint64 $.max-states is rw;
    has uint64 $.max-arcs is rw;
    has uint64 $.max-bytes is rw;
    has uint64 $.max-work is rw;
    has uint64 $.reserved0 is rw;
    has uint64 $.reserved1 is rw;
    multi method new(
        UInt:D :$max-states = 0, UInt:D :$max-arcs = 0,
        UInt:D :$max-bytes = 0, UInt:D :$max-work = 0,
        --> BudgetV2:D
    ) {
        my $flags = ($max-states ?? BUDGET-STATES !! 0) +|
            ($max-arcs ?? BUDGET-ARCS !! 0) +|
            ($max-bytes ?? BUDGET-BYTES !! 0) +|
            ($max-work ?? BUDGET-WORK !! 0);
        my $value = self.bless;
        $value.header.struct-size = nativesizeof(BudgetV2);
        $value.header.abi-version = TYPED-ABI-VERSION;
        $value.header.flags = $flags;
        $value.header.reserved = 0;
        $value.max-states = $max-states;
        $value.max-arcs = $max-arcs;
        $value.max-bytes = $max-bytes;
        $value.max-work = $max-work;
        $value.reserved0 = 0;
        $value.reserved1 = 0;
        $value
    }
}

our class OutcomeV2 is repr('CStruct') is export(:abi) {
    HAS AbiV2Header $.header is rw;
    has uint32 $.precision is rw;
    has uint32 $.completeness is rw;
    has uint32 $.applicability is rw;
    has uint32 $.termination is rw;
    has uint32 $.evidence is rw;
    has uint32 $.reserved0 is rw;
    has uint64 $.states is rw;
    has uint64 $.arcs is rw;
    has uint64 $.bytes is rw;
    has uint64 $.work is rw;
    has uint64 $.limitations is rw;
    has uint64 $.reserved1 is rw;
    multi method new(
        UInt:D :$precision!, UInt:D :$completeness!,
        UInt:D :$applicability!, UInt:D :$termination!,
        UInt:D :$evidence!, UInt:D :$states = 0,
        UInt:D :$arcs = 0, UInt:D :$bytes = 0,
        UInt:D :$work = 0, UInt:D :$limitations = 0,
        --> OutcomeV2:D
    ) {
        my $value = self.bless;
        $value.header.struct-size = nativesizeof(OutcomeV2);
        $value.header.abi-version = TYPED-ABI-VERSION;
        $value.header.flags = 0;
        $value.header.reserved = 0;
        $value.precision = $precision;
        $value.completeness = $completeness;
        $value.applicability = $applicability;
        $value.termination = $termination;
        $value.evidence = $evidence;
        $value.reserved0 = 0;
        $value.states = $states;
        $value.arcs = $arcs;
        $value.bytes = $bytes;
        $value.work = $work;
        $value.limitations = $limitations;
        $value.reserved1 = 0;
        $value
    }
}

our constant TYPE-KINDS is export(:metadata) = Map.new(
    'LlingWfstBuilder' => 'opaque',
    'LlingWfst' => 'opaque',
    'LlingSemiring' => 'opaque',
    'LlingSemiringWeight' => 'opaque',
    'LlingLatticeValue' => 'opaque',
    'LlingCancellationV2' => 'opaque',
    'VtResource' => 'imported-struct',
    'VtInterfaceId' => 'imported-struct',
    'VtWfstArc' => 'imported-struct',
    'VtSemiringValue' => 'imported-struct',
);

our constant TYPE-RAKU-REPRESENTATIONS is export(:metadata) = Map.new(
    'LlingWfstBuilder' => 'Pointer',
    'LlingWfst' => 'Pointer',
    'LlingSemiring' => 'Pointer',
    'LlingSemiringWeight' => 'Pointer',
    'LlingLatticeValue' => 'Pointer',
    'LlingCancellationV2' => 'Pointer',
    'VtResource' => 'Vinary::Tree::Interop::RawResource',
    'VtInterfaceId' => 'Vinary::Tree::Interop::InterfaceId',
    'VtWfstArc' => 'Vinary::Tree::Interop::WfstArc',
    'VtSemiringValue' => 'Vinary::Tree::Interop::SemiringValue',
);

our constant TYPE-OWNERSHIP is export(:metadata) = Map.new(
    'LlingWfstBuilder' => 'unique-mutable-handle',
    'LlingWfst' => 'unique-immutable-handle',
    'LlingSemiring' => 'unique-context-handle',
    'LlingSemiringWeight' => 'unique-provider-value-handle',
    'LlingLatticeValue' => 'unique-provider-value-handle',
    'LlingCancellationV2' => 'unique-cancellation-handle',
    'VtResource' => 'reference-counted-retain',
    'VtInterfaceId' => 'value-identity',
    'VtWfstArc' => 'value',
    'VtSemiringValue' => 'provider-managed-token',
);

our constant STRUCT-SIZES is export(:metadata) = Map.new(
    'LlingAbiV2Header' => 24,
    'LlingId128' => 16,
    'LlingDigest256' => 32,
    'LlingWfstDescriptorV2' => 120,
    'LlingBudgetV2' => 72,
    'LlingOutcomeV2' => 96,
);

our constant STRUCT-RAKU-SUPPORT is export(:metadata) = Map.new(
    'LlingAbiV2Header' => 'cstruct',
    'LlingId128' => 'pointer-only',
    'LlingDigest256' => 'pointer-only',
    'LlingWfstDescriptorV2' => 'pointer-only',
    'LlingBudgetV2' => 'cstruct',
    'LlingOutcomeV2' => 'cstruct',
);

our constant C-SIGNATURES is export(:metadata) = Map.new(
    'lling_abi_version' => 'LLING_LLANG_API uint32_t lling_abi_version(void);',
    'lling_llang_api_revision' => 'LLING_LLANG_API uint32_t lling_llang_api_revision(void);',
    'lling_last_error_message' => 'LLING_LLANG_API const char* lling_last_error_message(void);',
    'lling_semiring_open' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_open(const VtResource* resource, LlingSemiring** out_semiring);',
    'lling_semiring_free' => 'LLING_LLANG_API void lling_semiring_free(LlingSemiring* semiring);',
    'lling_semiring_weight_free' => 'LLING_LLANG_API void lling_semiring_weight_free(LlingSemiringWeight* weight);',
    'lling_semiring_properties' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_properties(const LlingSemiring* semiring, uint64_t* out_properties);',
    'lling_semiring_zero' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_zero(const LlingSemiring* semiring, LlingSemiringWeight** out_weight);',
    'lling_semiring_one' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_one(const LlingSemiring* semiring, LlingSemiringWeight** out_weight);',
    'lling_semiring_weight_clone' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_weight_clone(const LlingSemiringWeight* weight, LlingSemiringWeight** out_weight);',
    'lling_semiring_plus' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_plus(const LlingSemiring* semiring, const LlingSemiringWeight* left, const LlingSemiringWeight* right, LlingSemiringWeight** out_weight);',
    'lling_semiring_times' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_times(const LlingSemiring* semiring, const LlingSemiringWeight* left, const LlingSemiringWeight* right, LlingSemiringWeight** out_weight);',
    'lling_semiring_equal' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_equal(const LlingSemiring* semiring, const LlingSemiringWeight* left, const LlingSemiringWeight* right, uint8_t* out_equal);',
    'lling_semiring_approx_equal' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_approx_equal(const LlingSemiring* semiring, const LlingSemiringWeight* left, const LlingSemiringWeight* right, double epsilon, uint8_t* out_equal);',
    'lling_semiring_natural_order' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_natural_order(const LlingSemiring* semiring, const LlingSemiringWeight* left, const LlingSemiringWeight* right, int32_t* out_order);',
    'lling_semiring_divide' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_divide(const LlingSemiring* semiring, const LlingSemiringWeight* dividend, const LlingSemiringWeight* divisor, LlingSemiringWeight** out_weight, uint8_t* out_defined);',
    'lling_semiring_left_divide' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_left_divide(const LlingSemiring* semiring, const LlingSemiringWeight* value, const LlingSemiringWeight* divisor, LlingSemiringWeight** out_weight, uint8_t* out_defined);',
    'lling_semiring_star' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_star(const LlingSemiring* semiring, const LlingSemiringWeight* value, LlingSemiringWeight** out_weight, uint8_t* out_defined);',
    'lling_semiring_numerical_value' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_numerical_value(const LlingSemiring* semiring, const LlingSemiringWeight* value, double* out_value);',
    'lling_semiring_quantize' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_quantize(const LlingSemiring* semiring, const LlingSemiringWeight* value, double epsilon, int64_t* out_value);',
    'lling_semiring_to_probability' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_to_probability(const LlingSemiring* semiring, const LlingSemiringWeight* value, double* out_value);',
    'lling_semiring_closure_bound' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_closure_bound(const LlingSemiring* semiring, size_t* out_bound, uint8_t* out_known);',
    'lling_semiring_stable_bytes' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_stable_bytes(const LlingSemiring* semiring, const LlingSemiringWeight* value, uint8_t* out_bytes, size_t capacity, size_t* out_written, size_t* out_required);',
    'lling_semiring_diagnostic' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_diagnostic(const LlingSemiring* semiring, const LlingSemiringWeight* value, uint8_t* out_bytes, size_t capacity, size_t* out_written, size_t* out_required);',
    'lling_semiring_plus_many' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_plus_many(const LlingSemiring* semiring, const LlingSemiringWeight*const* weights, size_t count, LlingSemiringWeight** out_weight);',
    'lling_semiring_times_many' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_times_many(const LlingSemiring* semiring, const LlingSemiringWeight*const* weights, size_t count, LlingSemiringWeight** out_weight);',
    'lling_semiring_validate_laws' => 'LLING_LLANG_API LlingLlangStatus lling_semiring_validate_laws(const LlingSemiring* semiring, const LlingSemiringWeight*const* weights, size_t count, double epsilon);',
    'lling_lattice_open' => 'LLING_LLANG_API LlingLlangStatus lling_lattice_open(const VtResource* resource, LlingLatticeValue** out_value);',
    'lling_lattice_free' => 'LLING_LLANG_API void lling_lattice_free(LlingLatticeValue* value);',
    'lling_lattice_domain_id' => 'LLING_LLANG_API LlingLlangStatus lling_lattice_domain_id(const LlingLatticeValue* value, VtInterfaceId* out_domain);',
    'lling_lattice_flags' => 'LLING_LLANG_API LlingLlangStatus lling_lattice_flags(const LlingLatticeValue* value, uint64_t* out_flags);',
    'lling_lattice_join' => 'LLING_LLANG_API LlingLlangStatus lling_lattice_join(const LlingLatticeValue* left, const LlingLatticeValue* right, LlingLatticeValue** out_value);',
    'lling_lattice_meet' => 'LLING_LLANG_API LlingLlangStatus lling_lattice_meet(const LlingLatticeValue* left, const LlingLatticeValue* right, LlingLatticeValue** out_value);',
    'lling_lattice_equal' => 'LLING_LLANG_API LlingLlangStatus lling_lattice_equal(const LlingLatticeValue* left, const LlingLatticeValue* right, uint8_t* out_equal);',
    'lling_lattice_stable_bytes' => 'LLING_LLANG_API LlingLlangStatus lling_lattice_stable_bytes(const LlingLatticeValue* value, uint8_t* out_bytes, size_t capacity, size_t* out_written, size_t* out_required);',
    'lling_lattice_diagnostic' => 'LLING_LLANG_API LlingLlangStatus lling_lattice_diagnostic(const LlingLatticeValue* value, uint8_t* out_bytes, size_t capacity, size_t* out_written, size_t* out_required);',
    'lling_lattice_join_many' => 'LLING_LLANG_API LlingLlangStatus lling_lattice_join_many(const LlingLatticeValue* receiver, const LlingLatticeValue*const* others, size_t count, LlingLatticeValue** out_value);',
    'lling_lattice_meet_many' => 'LLING_LLANG_API LlingLlangStatus lling_lattice_meet_many(const LlingLatticeValue* receiver, const LlingLatticeValue*const* others, size_t count, LlingLatticeValue** out_value);',
    'lling_lattice_validate_laws' => 'LLING_LLANG_API LlingLlangStatus lling_lattice_validate_laws(const LlingLatticeValue*const* values, size_t count);',
    'lling_wfst_builder_new' => 'LLING_LLANG_API LlingLlangStatus lling_wfst_builder_new(LlingWfstBuilder** out_builder);',
    'lling_wfst_builder_free' => 'LLING_LLANG_API void lling_wfst_builder_free(LlingWfstBuilder* builder);',
    'lling_wfst_builder_reserve_states' => 'LLING_LLANG_API LlingLlangStatus lling_wfst_builder_reserve_states(LlingWfstBuilder* builder, size_t additional);',
    'lling_wfst_builder_add_state' => 'LLING_LLANG_API LlingLlangStatus lling_wfst_builder_add_state(LlingWfstBuilder* builder, uint32_t* out_state);',
    'lling_wfst_builder_set_start' => 'LLING_LLANG_API LlingLlangStatus lling_wfst_builder_set_start(LlingWfstBuilder* builder, uint32_t state);',
    'lling_wfst_builder_set_final' => 'LLING_LLANG_API LlingLlangStatus lling_wfst_builder_set_final(LlingWfstBuilder* builder, uint32_t state, double weight);',
    'lling_wfst_builder_clear_final' => 'LLING_LLANG_API LlingLlangStatus lling_wfst_builder_clear_final(LlingWfstBuilder* builder, uint32_t state);',
    'lling_wfst_builder_add_arc' => 'LLING_LLANG_API LlingLlangStatus lling_wfst_builder_add_arc(LlingWfstBuilder* builder, uint32_t from, uint64_t input_label, uint8_t has_input, uint64_t output_label, uint8_t has_output, uint32_t to, double weight);',
    'lling_wfst_builder_build' => 'LLING_LLANG_API LlingLlangStatus lling_wfst_builder_build(LlingWfstBuilder* builder, LlingWfst** out_wfst);',
    'lling_wfst_free' => 'LLING_LLANG_API void lling_wfst_free(LlingWfst* wfst);',
    'lling_wfst_import' => 'LLING_LLANG_API LlingLlangStatus lling_wfst_import(VtResource resource, LlingWfst** out_wfst);',
    'lling_wfst_import_ref' => 'LLING_LLANG_API LlingLlangStatus lling_wfst_import_ref(const VtResource* resource, LlingWfst** out_wfst);',
    'lling_wfst_compose' => 'LLING_LLANG_API LlingLlangStatus lling_wfst_compose(VtResource first, VtResource second, LlingWfst** out_wfst);',
    'lling_wfst_compose_refs' => 'LLING_LLANG_API LlingLlangStatus lling_wfst_compose_refs(const VtResource* first, const VtResource* second, LlingWfst** out_wfst);',
    'lling_wfst_resource' => 'LLING_LLANG_API LlingLlangStatus lling_wfst_resource(const LlingWfst* wfst, VtResource* out_resource);',
    'lling_resource_release' => 'LLING_LLANG_API void lling_resource_release(VtResource resource);',
    'lling_abi_v2_validate_header' => 'LLING_LLANG_API LlingLlangStatus lling_abi_v2_validate_header(const LlingAbiV2Header* header, uint32_t required_size, uint64_t known_flags);',
    'lling_abi_v2_validate_descriptor' => 'LLING_LLANG_API LlingLlangStatus lling_abi_v2_validate_descriptor(const LlingWfstDescriptorV2* descriptor, uint8_t* out_typed_evidence_allowed);',
    'lling_abi_v2_validate_budget' => 'LLING_LLANG_API LlingLlangStatus lling_abi_v2_validate_budget(const LlingBudgetV2* budget);',
    'lling_abi_v2_validate_outcome' => 'LLING_LLANG_API LlingLlangStatus lling_abi_v2_validate_outcome(const LlingOutcomeV2* outcome, uint8_t resource_present, uint8_t evidence_present, uint8_t* out_authoritative_exact);',
    'lling_abi_v2_identity_matches' => 'LLING_LLANG_API LlingLlangStatus lling_abi_v2_identity_matches(const LlingWfstDescriptorV2* expected, const LlingWfstDescriptorV2* observed, uint8_t* out_matches);',
    'lling_cancellation_v2_new' => 'LLING_LLANG_API LlingLlangStatus lling_cancellation_v2_new(LlingCancellationV2** out_cancellation);',
    'lling_cancellation_v2_request' => 'LLING_LLANG_API LlingLlangStatus lling_cancellation_v2_request(const LlingCancellationV2* cancellation, uint32_t reason);',
    'lling_cancellation_v2_reason' => 'LLING_LLANG_API LlingLlangStatus lling_cancellation_v2_reason(const LlingCancellationV2* cancellation, uint32_t* out_reason);',
    'lling_cancellation_v2_free' => 'LLING_LLANG_API LlingLlangStatus lling_cancellation_v2_free(LlingCancellationV2** cancellation);',
    'lling_raku_provider_configure' => 'LLING_RAKU_API VtStatus lling_raku_provider_configure(LlingRakuDrop drop, LlingRakuStart start, LlingRakuCount count, LlingRakuStateInfo state_info, LlingRakuStateArcs state_arcs);',
    'lling_raku_provider_create' => 'LLING_RAKU_API VtStatus lling_raku_provider_create(uint32_t unit_domain, uint32_t weight_domain, uint64_t flags, void* host_context, VtResource* out_resource);',
    'lling_raku_semiring_configure_lifecycle' => 'LLING_RAKU_API VtStatus lling_raku_semiring_configure_lifecycle(LlingRakuDrop drop, LlingRakuSemiringIdentity zero, LlingRakuSemiringIdentity one, LlingRakuSemiringClone clone_value, LlingRakuSemiringRelease release_values);',
    'lling_raku_semiring_configure_algebra' => 'LLING_RAKU_API VtStatus lling_raku_semiring_configure_algebra(LlingRakuSemiringBinary plus, LlingRakuSemiringBinary times, LlingRakuSemiringEqual equal, LlingRakuSemiringApprox approx_equal, LlingRakuSemiringOrder natural_order);',
    'lling_raku_semiring_configure_buffers' => 'LLING_RAKU_API VtStatus lling_raku_semiring_configure_buffers(LlingRakuSemiringBytes stable_bytes, LlingRakuSemiringBytes diagnostic, LlingRakuSemiringMany plus_many, LlingRakuSemiringMany times_many);',
    'lling_raku_semiring_configure_optional' => 'LLING_RAKU_API VtStatus lling_raku_semiring_configure_optional(LlingRakuSemiringBinary divide, LlingRakuSemiringBinary left_divide, LlingRakuSemiringUnary star, LlingRakuSemiringNumerical numerical_value, LlingRakuSemiringNumerical to_probability);',
    'lling_raku_semiring_configure_metadata' => 'LLING_RAKU_API VtStatus lling_raku_semiring_configure_metadata(LlingRakuSemiringQuantize quantize, LlingRakuSemiringClosure closure_bound);',
    'lling_raku_semiring_create' => 'LLING_RAKU_API VtStatus lling_raku_semiring_create(uint64_t flags, const VtInterfaceId* domain_id, uint64_t properties, uint8_t has_division, uint8_t has_star, uint8_t has_numeric, void* host_context, VtResource* out_resource);',
);

our constant CALLBACK-SIGNATURES is export(:metadata) = Map.new(
    'LlingRakuDrop' => 'typedef void (*LlingRakuDrop)(void* host_context);',
    'LlingRakuStart' => 'typedef VtStatus (*LlingRakuStart)(void* host_context, uint64_t* out_state);',
    'LlingRakuCount' => 'typedef VtStatus (*LlingRakuCount)(void* host_context, size_t* out_count, uint8_t* out_known);',
    'LlingRakuStateInfo' => 'typedef VtStatus (*LlingRakuStateInfo)(void* host_context, uint64_t state, uint8_t* out_valid, uint8_t* out_is_final, double* out_final_weight);',
    'LlingRakuStateArcs' => 'typedef VtStatus (*LlingRakuStateArcs)(void* host_context, uint64_t state, size_t start, VtWfstArc* out_arcs, size_t capacity, size_t* out_written, size_t* out_total);',
    'LlingRakuSemiringIdentity' => 'typedef VtStatus (*LlingRakuSemiringIdentity)(void* host_context, VtSemiringValue* out_value);',
    'LlingRakuSemiringClone' => 'typedef VtStatus (*LlingRakuSemiringClone)(void* host_context, const VtSemiringValue* value, VtSemiringValue* out_value);',
    'LlingRakuSemiringRelease' => 'typedef VtStatus (*LlingRakuSemiringRelease)(void* host_context, VtSemiringValue* values, size_t count);',
    'LlingRakuSemiringBinary' => 'typedef VtStatus (*LlingRakuSemiringBinary)(void* host_context, const VtSemiringValue* left, const VtSemiringValue* right, VtSemiringValue* out_value);',
    'LlingRakuSemiringEqual' => 'typedef VtStatus (*LlingRakuSemiringEqual)(void* host_context, const VtSemiringValue* left, const VtSemiringValue* right, uint8_t* out_equal);',
    'LlingRakuSemiringApprox' => 'typedef VtStatus (*LlingRakuSemiringApprox)(void* host_context, const VtSemiringValue* left, const VtSemiringValue* right, double epsilon, uint8_t* out_equal);',
    'LlingRakuSemiringOrder' => 'typedef VtStatus (*LlingRakuSemiringOrder)(void* host_context, const VtSemiringValue* left, const VtSemiringValue* right, int32_t* out_order);',
    'LlingRakuSemiringBytes' => 'typedef VtStatus (*LlingRakuSemiringBytes)(void* host_context, const VtSemiringValue* value, uint8_t* out_bytes, size_t capacity, size_t* out_written, size_t* out_required);',
    'LlingRakuSemiringMany' => 'typedef VtStatus (*LlingRakuSemiringMany)(void* host_context, const VtSemiringValue* values, size_t count, VtSemiringValue* out_value);',
    'LlingRakuSemiringUnary' => 'typedef VtStatus (*LlingRakuSemiringUnary)(void* host_context, const VtSemiringValue* value, VtSemiringValue* out_value);',
    'LlingRakuSemiringNumerical' => 'typedef VtStatus (*LlingRakuSemiringNumerical)(void* host_context, const VtSemiringValue* value, double* out_value);',
    'LlingRakuSemiringQuantize' => 'typedef VtStatus (*LlingRakuSemiringQuantize)(void* host_context, const VtSemiringValue* value, double epsilon, int64_t* out_value);',
    'LlingRakuSemiringClosure' => 'typedef VtStatus (*LlingRakuSemiringClosure)(void* host_context, size_t* out_bound, uint8_t* out_known);',
);

our constant CALLBACK-THREADING is export(:metadata) = Map.new(
    'LlingRakuDrop' => 'provider-declared-reentrancy',
    'LlingRakuStart' => 'provider-declared-reentrancy',
    'LlingRakuCount' => 'provider-declared-reentrancy',
    'LlingRakuStateInfo' => 'provider-declared-reentrancy',
    'LlingRakuStateArcs' => 'provider-declared-reentrancy',
    'LlingRakuSemiringIdentity' => 'provider-declared-reentrancy',
    'LlingRakuSemiringClone' => 'provider-declared-reentrancy',
    'LlingRakuSemiringRelease' => 'provider-declared-reentrancy',
    'LlingRakuSemiringBinary' => 'provider-declared-reentrancy',
    'LlingRakuSemiringEqual' => 'provider-declared-reentrancy',
    'LlingRakuSemiringApprox' => 'provider-declared-reentrancy',
    'LlingRakuSemiringOrder' => 'provider-declared-reentrancy',
    'LlingRakuSemiringBytes' => 'provider-declared-reentrancy',
    'LlingRakuSemiringMany' => 'provider-declared-reentrancy',
    'LlingRakuSemiringUnary' => 'provider-declared-reentrancy',
    'LlingRakuSemiringNumerical' => 'provider-declared-reentrancy',
    'LlingRakuSemiringQuantize' => 'provider-declared-reentrancy',
    'LlingRakuSemiringClosure' => 'provider-declared-reentrancy',
);

our constant FUNCTION-SINCE-API-REVISION is export(:metadata) = Map.new(
    'lling_abi_version' => 1,
    'lling_llang_api_revision' => 6,
    'lling_last_error_message' => 1,
    'lling_semiring_open' => 3,
    'lling_semiring_free' => 3,
    'lling_semiring_weight_free' => 3,
    'lling_semiring_properties' => 3,
    'lling_semiring_zero' => 3,
    'lling_semiring_one' => 3,
    'lling_semiring_weight_clone' => 3,
    'lling_semiring_plus' => 3,
    'lling_semiring_times' => 3,
    'lling_semiring_equal' => 3,
    'lling_semiring_approx_equal' => 3,
    'lling_semiring_natural_order' => 3,
    'lling_semiring_divide' => 3,
    'lling_semiring_left_divide' => 3,
    'lling_semiring_star' => 3,
    'lling_semiring_numerical_value' => 3,
    'lling_semiring_quantize' => 3,
    'lling_semiring_to_probability' => 3,
    'lling_semiring_closure_bound' => 3,
    'lling_semiring_stable_bytes' => 3,
    'lling_semiring_diagnostic' => 3,
    'lling_semiring_plus_many' => 3,
    'lling_semiring_times_many' => 3,
    'lling_semiring_validate_laws' => 3,
    'lling_lattice_open' => 4,
    'lling_lattice_free' => 4,
    'lling_lattice_domain_id' => 4,
    'lling_lattice_flags' => 4,
    'lling_lattice_join' => 4,
    'lling_lattice_meet' => 4,
    'lling_lattice_equal' => 4,
    'lling_lattice_stable_bytes' => 4,
    'lling_lattice_diagnostic' => 4,
    'lling_lattice_join_many' => 4,
    'lling_lattice_meet_many' => 4,
    'lling_lattice_validate_laws' => 4,
    'lling_wfst_builder_new' => 1,
    'lling_wfst_builder_free' => 1,
    'lling_wfst_builder_reserve_states' => 1,
    'lling_wfst_builder_add_state' => 1,
    'lling_wfst_builder_set_start' => 1,
    'lling_wfst_builder_set_final' => 1,
    'lling_wfst_builder_clear_final' => 1,
    'lling_wfst_builder_add_arc' => 1,
    'lling_wfst_builder_build' => 1,
    'lling_wfst_free' => 1,
    'lling_wfst_import' => 1,
    'lling_wfst_import_ref' => 2,
    'lling_wfst_compose' => 1,
    'lling_wfst_compose_refs' => 2,
    'lling_wfst_resource' => 1,
    'lling_resource_release' => 1,
    'lling_abi_v2_validate_header' => 2,
    'lling_abi_v2_validate_descriptor' => 2,
    'lling_abi_v2_validate_budget' => 2,
    'lling_abi_v2_validate_outcome' => 2,
    'lling_abi_v2_identity_matches' => 2,
    'lling_cancellation_v2_new' => 2,
    'lling_cancellation_v2_request' => 2,
    'lling_cancellation_v2_reason' => 2,
    'lling_cancellation_v2_free' => 2,
    'lling_raku_provider_configure' => 2,
    'lling_raku_provider_create' => 2,
    'lling_raku_semiring_configure_lifecycle' => 3,
    'lling_raku_semiring_configure_algebra' => 3,
    'lling_raku_semiring_configure_buffers' => 3,
    'lling_raku_semiring_configure_optional' => 3,
    'lling_raku_semiring_configure_metadata' => 3,
    'lling_raku_semiring_create' => 3,
);

our constant FUNCTION-THREADING is export(:metadata) = Map.new(
    'lling_abi_version' => 'concurrent-reentrant',
    'lling_llang_api_revision' => 'concurrent-reentrant',
    'lling_last_error_message' => 'caller-thread-thread-local-error-buffer',
    'lling_semiring_open' => 'provider-declared-thread-contract',
    'lling_semiring_free' => 'exclusive-owner-close',
    'lling_semiring_weight_free' => 'exclusive-owner-close',
    'lling_semiring_properties' => 'provider-declared-thread-contract',
    'lling_semiring_zero' => 'provider-declared-thread-contract',
    'lling_semiring_one' => 'provider-declared-thread-contract',
    'lling_semiring_weight_clone' => 'provider-declared-thread-contract',
    'lling_semiring_plus' => 'provider-declared-thread-contract',
    'lling_semiring_times' => 'provider-declared-thread-contract',
    'lling_semiring_equal' => 'provider-declared-thread-contract',
    'lling_semiring_approx_equal' => 'provider-declared-thread-contract',
    'lling_semiring_natural_order' => 'provider-declared-thread-contract',
    'lling_semiring_divide' => 'provider-declared-thread-contract',
    'lling_semiring_left_divide' => 'provider-declared-thread-contract',
    'lling_semiring_star' => 'provider-declared-thread-contract',
    'lling_semiring_numerical_value' => 'provider-declared-thread-contract',
    'lling_semiring_quantize' => 'provider-declared-thread-contract',
    'lling_semiring_to_probability' => 'provider-declared-thread-contract',
    'lling_semiring_closure_bound' => 'provider-declared-thread-contract',
    'lling_semiring_stable_bytes' => 'provider-declared-thread-contract',
    'lling_semiring_diagnostic' => 'provider-declared-thread-contract',
    'lling_semiring_plus_many' => 'provider-declared-thread-contract',
    'lling_semiring_times_many' => 'provider-declared-thread-contract',
    'lling_semiring_validate_laws' => 'provider-declared-thread-contract',
    'lling_lattice_open' => 'same-thread-resource-contract',
    'lling_lattice_free' => 'exclusive-owner-close',
    'lling_lattice_domain_id' => 'same-thread-resource-contract',
    'lling_lattice_flags' => 'same-thread-resource-contract',
    'lling_lattice_join' => 'same-thread-resource-contract',
    'lling_lattice_meet' => 'same-thread-resource-contract',
    'lling_lattice_equal' => 'same-thread-resource-contract',
    'lling_lattice_stable_bytes' => 'same-thread-resource-contract',
    'lling_lattice_diagnostic' => 'same-thread-resource-contract',
    'lling_lattice_join_many' => 'same-thread-resource-contract',
    'lling_lattice_meet_many' => 'same-thread-resource-contract',
    'lling_lattice_validate_laws' => 'same-thread-resource-contract',
    'lling_wfst_builder_new' => 'caller-synchronized-mutable-handle',
    'lling_wfst_builder_free' => 'exclusive-owner-close',
    'lling_wfst_builder_reserve_states' => 'caller-synchronized-mutable-handle',
    'lling_wfst_builder_add_state' => 'caller-synchronized-mutable-handle',
    'lling_wfst_builder_set_start' => 'caller-synchronized-mutable-handle',
    'lling_wfst_builder_set_final' => 'caller-synchronized-mutable-handle',
    'lling_wfst_builder_clear_final' => 'caller-synchronized-mutable-handle',
    'lling_wfst_builder_add_arc' => 'caller-synchronized-mutable-handle',
    'lling_wfst_builder_build' => 'caller-synchronized-mutable-handle',
    'lling_wfst_free' => 'exclusive-owner-close',
    'lling_wfst_import' => 'caller-coordinates-immutable-handle-lifetime',
    'lling_wfst_import_ref' => 'caller-coordinates-immutable-handle-lifetime',
    'lling_wfst_compose' => 'caller-coordinates-immutable-handle-lifetime',
    'lling_wfst_compose_refs' => 'caller-coordinates-immutable-handle-lifetime',
    'lling_wfst_resource' => 'caller-coordinates-immutable-handle-lifetime',
    'lling_resource_release' => 'exclusive-owner-close',
    'lling_abi_v2_validate_header' => 'concurrent-reentrant',
    'lling_abi_v2_validate_descriptor' => 'concurrent-reentrant',
    'lling_abi_v2_validate_budget' => 'concurrent-reentrant',
    'lling_abi_v2_validate_outcome' => 'concurrent-reentrant',
    'lling_abi_v2_identity_matches' => 'concurrent-reentrant',
    'lling_cancellation_v2_new' => 'concurrent-reentrant-cancellation-token',
    'lling_cancellation_v2_request' => 'concurrent-reentrant-cancellation-token',
    'lling_cancellation_v2_reason' => 'concurrent-reentrant-cancellation-token',
    'lling_cancellation_v2_free' => 'exclusive-owner-close',
    'lling_raku_provider_configure' => 'configure-once-process-global',
    'lling_raku_provider_create' => 'caller-thread-provider-construction',
    'lling_raku_semiring_configure_lifecycle' => 'configure-once-process-global',
    'lling_raku_semiring_configure_algebra' => 'configure-once-process-global',
    'lling_raku_semiring_configure_buffers' => 'configure-once-process-global',
    'lling_raku_semiring_configure_optional' => 'configure-once-process-global',
    'lling_raku_semiring_configure_metadata' => 'configure-once-process-global',
    'lling_raku_semiring_create' => 'caller-thread-provider-construction',
);

our constant FUNCTION-CAPABILITIES is export(:metadata) = Map.new(
    'lling_abi_version' => 'core-versioning',
    'lling_llang_api_revision' => 'core-versioning',
    'lling_last_error_message' => 'core-versioning',
    'lling_semiring_open' => 'semiring-consumer',
    'lling_semiring_free' => 'semiring-consumer',
    'lling_semiring_weight_free' => 'semiring-consumer',
    'lling_semiring_properties' => 'semiring-consumer',
    'lling_semiring_zero' => 'semiring-consumer',
    'lling_semiring_one' => 'semiring-consumer',
    'lling_semiring_weight_clone' => 'semiring-consumer',
    'lling_semiring_plus' => 'semiring-consumer',
    'lling_semiring_times' => 'semiring-consumer',
    'lling_semiring_equal' => 'semiring-consumer',
    'lling_semiring_approx_equal' => 'semiring-consumer',
    'lling_semiring_natural_order' => 'semiring-consumer',
    'lling_semiring_divide' => 'semiring-consumer',
    'lling_semiring_left_divide' => 'semiring-consumer',
    'lling_semiring_star' => 'semiring-consumer',
    'lling_semiring_numerical_value' => 'semiring-consumer',
    'lling_semiring_quantize' => 'semiring-consumer',
    'lling_semiring_to_probability' => 'semiring-consumer',
    'lling_semiring_closure_bound' => 'semiring-consumer',
    'lling_semiring_stable_bytes' => 'semiring-consumer',
    'lling_semiring_diagnostic' => 'semiring-consumer',
    'lling_semiring_plus_many' => 'semiring-consumer',
    'lling_semiring_times_many' => 'semiring-consumer',
    'lling_semiring_validate_laws' => 'semiring-consumer',
    'lling_lattice_open' => 'lattice-consumer',
    'lling_lattice_free' => 'lattice-consumer',
    'lling_lattice_domain_id' => 'lattice-consumer',
    'lling_lattice_flags' => 'lattice-consumer',
    'lling_lattice_join' => 'lattice-consumer',
    'lling_lattice_meet' => 'lattice-consumer',
    'lling_lattice_equal' => 'lattice-consumer',
    'lling_lattice_stable_bytes' => 'lattice-consumer',
    'lling_lattice_diagnostic' => 'lattice-consumer',
    'lling_lattice_join_many' => 'lattice-consumer',
    'lling_lattice_meet_many' => 'lattice-consumer',
    'lling_lattice_validate_laws' => 'lattice-consumer',
    'lling_wfst_builder_new' => 'wfst-builder',
    'lling_wfst_builder_free' => 'wfst-builder',
    'lling_wfst_builder_reserve_states' => 'wfst-builder',
    'lling_wfst_builder_add_state' => 'wfst-builder',
    'lling_wfst_builder_set_start' => 'wfst-builder',
    'lling_wfst_builder_set_final' => 'wfst-builder',
    'lling_wfst_builder_clear_final' => 'wfst-builder',
    'lling_wfst_builder_add_arc' => 'wfst-builder',
    'lling_wfst_builder_build' => 'wfst-builder',
    'lling_wfst_free' => 'wfst-resource',
    'lling_wfst_import' => 'wfst-resource',
    'lling_wfst_import_ref' => 'wfst-resource',
    'lling_wfst_compose' => 'wfst-resource',
    'lling_wfst_compose_refs' => 'wfst-resource',
    'lling_wfst_resource' => 'wfst-resource',
    'lling_resource_release' => 'wfst-resource',
    'lling_abi_v2_validate_header' => 'typed-abi-v2',
    'lling_abi_v2_validate_descriptor' => 'typed-abi-v2',
    'lling_abi_v2_validate_budget' => 'typed-abi-v2',
    'lling_abi_v2_validate_outcome' => 'typed-abi-v2',
    'lling_abi_v2_identity_matches' => 'typed-abi-v2',
    'lling_cancellation_v2_new' => 'cancellation-v2',
    'lling_cancellation_v2_request' => 'cancellation-v2',
    'lling_cancellation_v2_reason' => 'cancellation-v2',
    'lling_cancellation_v2_free' => 'cancellation-v2',
    'lling_raku_provider_configure' => 'WFST_PROVIDER',
    'lling_raku_provider_create' => 'WFST_PROVIDER',
    'lling_raku_semiring_configure_lifecycle' => 'SEMIRING_BASE',
    'lling_raku_semiring_configure_algebra' => 'SEMIRING_BASE',
    'lling_raku_semiring_configure_buffers' => 'SEMIRING_BATCH',
    'lling_raku_semiring_configure_optional' => 'SEMIRING_OPTIONAL',
    'lling_raku_semiring_configure_metadata' => 'SEMIRING_PROPERTIES',
    'lling_raku_semiring_create' => 'SEMIRING_BASE',
);

our constant FUNCTION-OWNERSHIP is export(:metadata) = Map.new(
    'lling_abi_version:return' => 'value',
    'lling_llang_api_revision:return' => 'value',
    'lling_last_error_message:return' => 'borrowed-thread-local-until-next-boundary-call',
    'lling_semiring_open:return' => 'value',
    'lling_semiring_open:resource' => 'borrowed-capture-retain',
    'lling_semiring_open:out_semiring' => 'owned-output-on-success',
    'lling_semiring_free:return' => 'none',
    'lling_semiring_free:semiring' => 'consumed-when-non-null',
    'lling_semiring_weight_free:return' => 'none',
    'lling_semiring_weight_free:weight' => 'consumed-when-non-null',
    'lling_semiring_properties:return' => 'value',
    'lling_semiring_properties:semiring' => 'borrowed-for-call',
    'lling_semiring_properties:out_properties' => 'borrowed-output-slot',
    'lling_semiring_zero:return' => 'value',
    'lling_semiring_zero:semiring' => 'borrowed-for-call',
    'lling_semiring_zero:out_weight' => 'owned-output-on-success',
    'lling_semiring_one:return' => 'value',
    'lling_semiring_one:semiring' => 'borrowed-for-call',
    'lling_semiring_one:out_weight' => 'owned-output-on-success',
    'lling_semiring_weight_clone:return' => 'value',
    'lling_semiring_weight_clone:weight' => 'borrowed-for-call',
    'lling_semiring_weight_clone:out_weight' => 'owned-output-on-success',
    'lling_semiring_plus:return' => 'value',
    'lling_semiring_plus:semiring' => 'borrowed-for-call',
    'lling_semiring_plus:left' => 'borrowed-for-call',
    'lling_semiring_plus:right' => 'borrowed-for-call',
    'lling_semiring_plus:out_weight' => 'owned-output-on-success',
    'lling_semiring_times:return' => 'value',
    'lling_semiring_times:semiring' => 'borrowed-for-call',
    'lling_semiring_times:left' => 'borrowed-for-call',
    'lling_semiring_times:right' => 'borrowed-for-call',
    'lling_semiring_times:out_weight' => 'owned-output-on-success',
    'lling_semiring_equal:return' => 'value',
    'lling_semiring_equal:semiring' => 'borrowed-for-call',
    'lling_semiring_equal:left' => 'borrowed-for-call',
    'lling_semiring_equal:right' => 'borrowed-for-call',
    'lling_semiring_equal:out_equal' => 'borrowed-output-slot',
    'lling_semiring_approx_equal:return' => 'value',
    'lling_semiring_approx_equal:semiring' => 'borrowed-for-call',
    'lling_semiring_approx_equal:left' => 'borrowed-for-call',
    'lling_semiring_approx_equal:right' => 'borrowed-for-call',
    'lling_semiring_approx_equal:epsilon' => 'value',
    'lling_semiring_approx_equal:out_equal' => 'borrowed-output-slot',
    'lling_semiring_natural_order:return' => 'value',
    'lling_semiring_natural_order:semiring' => 'borrowed-for-call',
    'lling_semiring_natural_order:left' => 'borrowed-for-call',
    'lling_semiring_natural_order:right' => 'borrowed-for-call',
    'lling_semiring_natural_order:out_order' => 'borrowed-output-slot',
    'lling_semiring_divide:return' => 'value',
    'lling_semiring_divide:semiring' => 'borrowed-for-call',
    'lling_semiring_divide:dividend' => 'borrowed-for-call',
    'lling_semiring_divide:divisor' => 'borrowed-for-call',
    'lling_semiring_divide:out_weight' => 'owned-output-on-success',
    'lling_semiring_divide:out_defined' => 'borrowed-output-slot',
    'lling_semiring_left_divide:return' => 'value',
    'lling_semiring_left_divide:semiring' => 'borrowed-for-call',
    'lling_semiring_left_divide:value' => 'borrowed-for-call',
    'lling_semiring_left_divide:divisor' => 'borrowed-for-call',
    'lling_semiring_left_divide:out_weight' => 'owned-output-on-success',
    'lling_semiring_left_divide:out_defined' => 'borrowed-output-slot',
    'lling_semiring_star:return' => 'value',
    'lling_semiring_star:semiring' => 'borrowed-for-call',
    'lling_semiring_star:value' => 'borrowed-for-call',
    'lling_semiring_star:out_weight' => 'owned-output-on-success',
    'lling_semiring_star:out_defined' => 'borrowed-output-slot',
    'lling_semiring_numerical_value:return' => 'value',
    'lling_semiring_numerical_value:semiring' => 'borrowed-for-call',
    'lling_semiring_numerical_value:value' => 'borrowed-for-call',
    'lling_semiring_numerical_value:out_value' => 'borrowed-output-slot',
    'lling_semiring_quantize:return' => 'value',
    'lling_semiring_quantize:semiring' => 'borrowed-for-call',
    'lling_semiring_quantize:value' => 'borrowed-for-call',
    'lling_semiring_quantize:epsilon' => 'value',
    'lling_semiring_quantize:out_value' => 'borrowed-output-slot',
    'lling_semiring_to_probability:return' => 'value',
    'lling_semiring_to_probability:semiring' => 'borrowed-for-call',
    'lling_semiring_to_probability:value' => 'borrowed-for-call',
    'lling_semiring_to_probability:out_value' => 'borrowed-output-slot',
    'lling_semiring_closure_bound:return' => 'value',
    'lling_semiring_closure_bound:semiring' => 'borrowed-for-call',
    'lling_semiring_closure_bound:out_bound' => 'borrowed-output-slot',
    'lling_semiring_closure_bound:out_known' => 'borrowed-output-slot',
    'lling_semiring_stable_bytes:return' => 'value',
    'lling_semiring_stable_bytes:semiring' => 'borrowed-for-call',
    'lling_semiring_stable_bytes:value' => 'borrowed-for-call',
    'lling_semiring_stable_bytes:out_bytes' => 'borrowed-output-buffer',
    'lling_semiring_stable_bytes:capacity' => 'value',
    'lling_semiring_stable_bytes:out_written' => 'borrowed-output-slot',
    'lling_semiring_stable_bytes:out_required' => 'borrowed-output-slot',
    'lling_semiring_diagnostic:return' => 'value',
    'lling_semiring_diagnostic:semiring' => 'borrowed-for-call',
    'lling_semiring_diagnostic:value' => 'borrowed-for-call',
    'lling_semiring_diagnostic:out_bytes' => 'borrowed-output-buffer',
    'lling_semiring_diagnostic:capacity' => 'value',
    'lling_semiring_diagnostic:out_written' => 'borrowed-output-slot',
    'lling_semiring_diagnostic:out_required' => 'borrowed-output-slot',
    'lling_semiring_plus_many:return' => 'value',
    'lling_semiring_plus_many:semiring' => 'borrowed-for-call',
    'lling_semiring_plus_many:weights' => 'borrowed-array-for-call',
    'lling_semiring_plus_many:count' => 'value',
    'lling_semiring_plus_many:out_weight' => 'owned-output-on-success',
    'lling_semiring_times_many:return' => 'value',
    'lling_semiring_times_many:semiring' => 'borrowed-for-call',
    'lling_semiring_times_many:weights' => 'borrowed-array-for-call',
    'lling_semiring_times_many:count' => 'value',
    'lling_semiring_times_many:out_weight' => 'owned-output-on-success',
    'lling_semiring_validate_laws:return' => 'value',
    'lling_semiring_validate_laws:semiring' => 'borrowed-for-call',
    'lling_semiring_validate_laws:weights' => 'borrowed-array-for-call',
    'lling_semiring_validate_laws:count' => 'value',
    'lling_semiring_validate_laws:epsilon' => 'value',
    'lling_lattice_open:return' => 'value',
    'lling_lattice_open:resource' => 'borrowed-capture-retain',
    'lling_lattice_open:out_value' => 'owned-output-on-success',
    'lling_lattice_free:return' => 'none',
    'lling_lattice_free:value' => 'consumed-when-non-null',
    'lling_lattice_domain_id:return' => 'value',
    'lling_lattice_domain_id:value' => 'borrowed-for-call',
    'lling_lattice_domain_id:out_domain' => 'borrowed-output-slot',
    'lling_lattice_flags:return' => 'value',
    'lling_lattice_flags:value' => 'borrowed-for-call',
    'lling_lattice_flags:out_flags' => 'borrowed-output-slot',
    'lling_lattice_join:return' => 'value',
    'lling_lattice_join:left' => 'borrowed-for-call',
    'lling_lattice_join:right' => 'borrowed-for-call',
    'lling_lattice_join:out_value' => 'owned-output-on-success',
    'lling_lattice_meet:return' => 'value',
    'lling_lattice_meet:left' => 'borrowed-for-call',
    'lling_lattice_meet:right' => 'borrowed-for-call',
    'lling_lattice_meet:out_value' => 'owned-output-on-success',
    'lling_lattice_equal:return' => 'value',
    'lling_lattice_equal:left' => 'borrowed-for-call',
    'lling_lattice_equal:right' => 'borrowed-for-call',
    'lling_lattice_equal:out_equal' => 'borrowed-output-slot',
    'lling_lattice_stable_bytes:return' => 'value',
    'lling_lattice_stable_bytes:value' => 'borrowed-for-call',
    'lling_lattice_stable_bytes:out_bytes' => 'borrowed-output-buffer',
    'lling_lattice_stable_bytes:capacity' => 'value',
    'lling_lattice_stable_bytes:out_written' => 'borrowed-output-slot',
    'lling_lattice_stable_bytes:out_required' => 'borrowed-output-slot',
    'lling_lattice_diagnostic:return' => 'value',
    'lling_lattice_diagnostic:value' => 'borrowed-for-call',
    'lling_lattice_diagnostic:out_bytes' => 'borrowed-output-buffer',
    'lling_lattice_diagnostic:capacity' => 'value',
    'lling_lattice_diagnostic:out_written' => 'borrowed-output-slot',
    'lling_lattice_diagnostic:out_required' => 'borrowed-output-slot',
    'lling_lattice_join_many:return' => 'value',
    'lling_lattice_join_many:receiver' => 'borrowed-for-call',
    'lling_lattice_join_many:others' => 'borrowed-array-for-call',
    'lling_lattice_join_many:count' => 'value',
    'lling_lattice_join_many:out_value' => 'owned-output-on-success',
    'lling_lattice_meet_many:return' => 'value',
    'lling_lattice_meet_many:receiver' => 'borrowed-for-call',
    'lling_lattice_meet_many:others' => 'borrowed-array-for-call',
    'lling_lattice_meet_many:count' => 'value',
    'lling_lattice_meet_many:out_value' => 'owned-output-on-success',
    'lling_lattice_validate_laws:return' => 'value',
    'lling_lattice_validate_laws:values' => 'borrowed-array-for-call',
    'lling_lattice_validate_laws:count' => 'value',
    'lling_wfst_builder_new:return' => 'value',
    'lling_wfst_builder_new:out_builder' => 'owned-output-on-success',
    'lling_wfst_builder_free:return' => 'none',
    'lling_wfst_builder_free:builder' => 'consumed-when-non-null',
    'lling_wfst_builder_reserve_states:return' => 'value',
    'lling_wfst_builder_reserve_states:builder' => 'borrowed-for-call',
    'lling_wfst_builder_reserve_states:additional' => 'value',
    'lling_wfst_builder_add_state:return' => 'value',
    'lling_wfst_builder_add_state:builder' => 'borrowed-for-call',
    'lling_wfst_builder_add_state:out_state' => 'borrowed-output-slot',
    'lling_wfst_builder_set_start:return' => 'value',
    'lling_wfst_builder_set_start:builder' => 'borrowed-for-call',
    'lling_wfst_builder_set_start:state' => 'value',
    'lling_wfst_builder_set_final:return' => 'value',
    'lling_wfst_builder_set_final:builder' => 'borrowed-for-call',
    'lling_wfst_builder_set_final:state' => 'value',
    'lling_wfst_builder_set_final:weight' => 'value',
    'lling_wfst_builder_clear_final:return' => 'value',
    'lling_wfst_builder_clear_final:builder' => 'borrowed-for-call',
    'lling_wfst_builder_clear_final:state' => 'value',
    'lling_wfst_builder_add_arc:return' => 'value',
    'lling_wfst_builder_add_arc:builder' => 'borrowed-for-call',
    'lling_wfst_builder_add_arc:from' => 'value',
    'lling_wfst_builder_add_arc:input_label' => 'value',
    'lling_wfst_builder_add_arc:has_input' => 'value',
    'lling_wfst_builder_add_arc:output_label' => 'value',
    'lling_wfst_builder_add_arc:has_output' => 'value',
    'lling_wfst_builder_add_arc:to' => 'value',
    'lling_wfst_builder_add_arc:weight' => 'value',
    'lling_wfst_builder_build:return' => 'value',
    'lling_wfst_builder_build:builder' => 'borrowed-consuming-graph-on-success',
    'lling_wfst_builder_build:out_wfst' => 'owned-output-on-success',
    'lling_wfst_free:return' => 'none',
    'lling_wfst_free:wfst' => 'consumed-when-non-null',
    'lling_wfst_import:return' => 'value',
    'lling_wfst_import:resource' => 'borrowed-capture-snapshot',
    'lling_wfst_import:out_wfst' => 'owned-output-on-success',
    'lling_wfst_import_ref:return' => 'value',
    'lling_wfst_import_ref:resource' => 'borrowed-capture-snapshot',
    'lling_wfst_import_ref:out_wfst' => 'owned-output-on-success',
    'lling_wfst_compose:return' => 'value',
    'lling_wfst_compose:first' => 'borrowed-capture-snapshot',
    'lling_wfst_compose:second' => 'borrowed-capture-snapshot',
    'lling_wfst_compose:out_wfst' => 'owned-output-on-success',
    'lling_wfst_compose_refs:return' => 'value',
    'lling_wfst_compose_refs:first' => 'borrowed-capture-snapshot',
    'lling_wfst_compose_refs:second' => 'borrowed-capture-snapshot',
    'lling_wfst_compose_refs:out_wfst' => 'owned-output-on-success',
    'lling_wfst_resource:return' => 'value',
    'lling_wfst_resource:wfst' => 'borrowed-for-call',
    'lling_wfst_resource:out_resource' => 'owned-retain-on-success',
    'lling_resource_release:return' => 'none',
    'lling_resource_release:resource' => 'consumed-retain',
    'lling_abi_v2_validate_header:return' => 'value',
    'lling_abi_v2_validate_header:header' => 'borrowed-for-call',
    'lling_abi_v2_validate_header:required_size' => 'value',
    'lling_abi_v2_validate_header:known_flags' => 'value',
    'lling_abi_v2_validate_descriptor:return' => 'value',
    'lling_abi_v2_validate_descriptor:descriptor' => 'borrowed-for-call',
    'lling_abi_v2_validate_descriptor:out_typed_evidence_allowed' => 'borrowed-output-slot',
    'lling_abi_v2_validate_budget:return' => 'value',
    'lling_abi_v2_validate_budget:budget' => 'borrowed-for-call',
    'lling_abi_v2_validate_outcome:return' => 'value',
    'lling_abi_v2_validate_outcome:outcome' => 'borrowed-for-call',
    'lling_abi_v2_validate_outcome:resource_present' => 'value',
    'lling_abi_v2_validate_outcome:evidence_present' => 'value',
    'lling_abi_v2_validate_outcome:out_authoritative_exact' => 'borrowed-output-slot',
    'lling_abi_v2_identity_matches:return' => 'value',
    'lling_abi_v2_identity_matches:expected' => 'borrowed-for-call',
    'lling_abi_v2_identity_matches:observed' => 'borrowed-for-call',
    'lling_abi_v2_identity_matches:out_matches' => 'borrowed-output-slot',
    'lling_cancellation_v2_new:return' => 'value',
    'lling_cancellation_v2_new:out_cancellation' => 'owned-output-on-success',
    'lling_cancellation_v2_request:return' => 'value',
    'lling_cancellation_v2_request:cancellation' => 'borrowed-for-call',
    'lling_cancellation_v2_request:reason' => 'value',
    'lling_cancellation_v2_reason:return' => 'value',
    'lling_cancellation_v2_reason:cancellation' => 'borrowed-for-call',
    'lling_cancellation_v2_reason:out_reason' => 'borrowed-output-slot',
    'lling_cancellation_v2_free:return' => 'value',
    'lling_cancellation_v2_free:cancellation' => 'consumed-and-cleared-on-success',
    'lling_raku_provider_configure:return' => 'value',
    'lling_raku_provider_configure:drop' => 'borrowed-process-lifetime',
    'lling_raku_provider_configure:start' => 'borrowed-process-lifetime',
    'lling_raku_provider_configure:count' => 'borrowed-process-lifetime',
    'lling_raku_provider_configure:state_info' => 'borrowed-process-lifetime',
    'lling_raku_provider_configure:state_arcs' => 'borrowed-process-lifetime',
    'lling_raku_provider_create:return' => 'value',
    'lling_raku_provider_create:unit_domain' => 'value',
    'lling_raku_provider_create:weight_domain' => 'value',
    'lling_raku_provider_create:flags' => 'value',
    'lling_raku_provider_create:host_context' => 'borrowed-for-call',
    'lling_raku_provider_create:out_resource' => 'owned-retain-on-success',
    'lling_raku_semiring_configure_lifecycle:return' => 'value',
    'lling_raku_semiring_configure_lifecycle:drop' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_lifecycle:zero' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_lifecycle:one' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_lifecycle:clone_value' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_lifecycle:release_values' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_algebra:return' => 'value',
    'lling_raku_semiring_configure_algebra:plus' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_algebra:times' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_algebra:equal' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_algebra:approx_equal' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_algebra:natural_order' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_buffers:return' => 'value',
    'lling_raku_semiring_configure_buffers:stable_bytes' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_buffers:diagnostic' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_buffers:plus_many' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_buffers:times_many' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_optional:return' => 'value',
    'lling_raku_semiring_configure_optional:divide' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_optional:left_divide' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_optional:star' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_optional:numerical_value' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_optional:to_probability' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_metadata:return' => 'value',
    'lling_raku_semiring_configure_metadata:quantize' => 'borrowed-process-lifetime',
    'lling_raku_semiring_configure_metadata:closure_bound' => 'borrowed-process-lifetime',
    'lling_raku_semiring_create:return' => 'value',
    'lling_raku_semiring_create:flags' => 'value',
    'lling_raku_semiring_create:domain_id' => 'borrowed-for-call',
    'lling_raku_semiring_create:properties' => 'value',
    'lling_raku_semiring_create:has_division' => 'value',
    'lling_raku_semiring_create:has_star' => 'value',
    'lling_raku_semiring_create:has_numeric' => 'value',
    'lling_raku_semiring_create:host_context' => 'borrowed-for-call',
    'lling_raku_semiring_create:out_resource' => 'owned-retain-on-success',
);

our constant FUNCTION-NULLABILITY is export(:metadata) = Map.new(
    'lling_abi_version:return' => 'not-applicable',
    'lling_llang_api_revision:return' => 'not-applicable',
    'lling_last_error_message:return' => 'non-null',
    'lling_semiring_open:return' => 'not-applicable',
    'lling_semiring_open:resource' => 'non-null',
    'lling_semiring_open:out_semiring' => 'non-null',
    'lling_semiring_free:return' => 'not-applicable',
    'lling_semiring_free:semiring' => 'nullable',
    'lling_semiring_weight_free:return' => 'not-applicable',
    'lling_semiring_weight_free:weight' => 'nullable',
    'lling_semiring_properties:return' => 'not-applicable',
    'lling_semiring_properties:semiring' => 'non-null',
    'lling_semiring_properties:out_properties' => 'non-null',
    'lling_semiring_zero:return' => 'not-applicable',
    'lling_semiring_zero:semiring' => 'non-null',
    'lling_semiring_zero:out_weight' => 'non-null',
    'lling_semiring_one:return' => 'not-applicable',
    'lling_semiring_one:semiring' => 'non-null',
    'lling_semiring_one:out_weight' => 'non-null',
    'lling_semiring_weight_clone:return' => 'not-applicable',
    'lling_semiring_weight_clone:weight' => 'non-null',
    'lling_semiring_weight_clone:out_weight' => 'non-null',
    'lling_semiring_plus:return' => 'not-applicable',
    'lling_semiring_plus:semiring' => 'non-null',
    'lling_semiring_plus:left' => 'non-null',
    'lling_semiring_plus:right' => 'non-null',
    'lling_semiring_plus:out_weight' => 'non-null',
    'lling_semiring_times:return' => 'not-applicable',
    'lling_semiring_times:semiring' => 'non-null',
    'lling_semiring_times:left' => 'non-null',
    'lling_semiring_times:right' => 'non-null',
    'lling_semiring_times:out_weight' => 'non-null',
    'lling_semiring_equal:return' => 'not-applicable',
    'lling_semiring_equal:semiring' => 'non-null',
    'lling_semiring_equal:left' => 'non-null',
    'lling_semiring_equal:right' => 'non-null',
    'lling_semiring_equal:out_equal' => 'non-null',
    'lling_semiring_approx_equal:return' => 'not-applicable',
    'lling_semiring_approx_equal:semiring' => 'non-null',
    'lling_semiring_approx_equal:left' => 'non-null',
    'lling_semiring_approx_equal:right' => 'non-null',
    'lling_semiring_approx_equal:epsilon' => 'not-applicable',
    'lling_semiring_approx_equal:out_equal' => 'non-null',
    'lling_semiring_natural_order:return' => 'not-applicable',
    'lling_semiring_natural_order:semiring' => 'non-null',
    'lling_semiring_natural_order:left' => 'non-null',
    'lling_semiring_natural_order:right' => 'non-null',
    'lling_semiring_natural_order:out_order' => 'non-null',
    'lling_semiring_divide:return' => 'not-applicable',
    'lling_semiring_divide:semiring' => 'non-null',
    'lling_semiring_divide:dividend' => 'non-null',
    'lling_semiring_divide:divisor' => 'non-null',
    'lling_semiring_divide:out_weight' => 'non-null',
    'lling_semiring_divide:out_defined' => 'non-null',
    'lling_semiring_left_divide:return' => 'not-applicable',
    'lling_semiring_left_divide:semiring' => 'non-null',
    'lling_semiring_left_divide:value' => 'non-null',
    'lling_semiring_left_divide:divisor' => 'non-null',
    'lling_semiring_left_divide:out_weight' => 'non-null',
    'lling_semiring_left_divide:out_defined' => 'non-null',
    'lling_semiring_star:return' => 'not-applicable',
    'lling_semiring_star:semiring' => 'non-null',
    'lling_semiring_star:value' => 'non-null',
    'lling_semiring_star:out_weight' => 'non-null',
    'lling_semiring_star:out_defined' => 'non-null',
    'lling_semiring_numerical_value:return' => 'not-applicable',
    'lling_semiring_numerical_value:semiring' => 'non-null',
    'lling_semiring_numerical_value:value' => 'non-null',
    'lling_semiring_numerical_value:out_value' => 'non-null',
    'lling_semiring_quantize:return' => 'not-applicable',
    'lling_semiring_quantize:semiring' => 'non-null',
    'lling_semiring_quantize:value' => 'non-null',
    'lling_semiring_quantize:epsilon' => 'not-applicable',
    'lling_semiring_quantize:out_value' => 'non-null',
    'lling_semiring_to_probability:return' => 'not-applicable',
    'lling_semiring_to_probability:semiring' => 'non-null',
    'lling_semiring_to_probability:value' => 'non-null',
    'lling_semiring_to_probability:out_value' => 'non-null',
    'lling_semiring_closure_bound:return' => 'not-applicable',
    'lling_semiring_closure_bound:semiring' => 'non-null',
    'lling_semiring_closure_bound:out_bound' => 'non-null',
    'lling_semiring_closure_bound:out_known' => 'non-null',
    'lling_semiring_stable_bytes:return' => 'not-applicable',
    'lling_semiring_stable_bytes:semiring' => 'non-null',
    'lling_semiring_stable_bytes:value' => 'non-null',
    'lling_semiring_stable_bytes:out_bytes' => 'nullable-if-capacity-is-zero',
    'lling_semiring_stable_bytes:capacity' => 'not-applicable',
    'lling_semiring_stable_bytes:out_written' => 'non-null',
    'lling_semiring_stable_bytes:out_required' => 'non-null',
    'lling_semiring_diagnostic:return' => 'not-applicable',
    'lling_semiring_diagnostic:semiring' => 'non-null',
    'lling_semiring_diagnostic:value' => 'non-null',
    'lling_semiring_diagnostic:out_bytes' => 'nullable-if-capacity-is-zero',
    'lling_semiring_diagnostic:capacity' => 'not-applicable',
    'lling_semiring_diagnostic:out_written' => 'non-null',
    'lling_semiring_diagnostic:out_required' => 'non-null',
    'lling_semiring_plus_many:return' => 'not-applicable',
    'lling_semiring_plus_many:semiring' => 'non-null',
    'lling_semiring_plus_many:weights' => 'nullable-if-count-is-zero',
    'lling_semiring_plus_many:count' => 'not-applicable',
    'lling_semiring_plus_many:out_weight' => 'non-null',
    'lling_semiring_times_many:return' => 'not-applicable',
    'lling_semiring_times_many:semiring' => 'non-null',
    'lling_semiring_times_many:weights' => 'nullable-if-count-is-zero',
    'lling_semiring_times_many:count' => 'not-applicable',
    'lling_semiring_times_many:out_weight' => 'non-null',
    'lling_semiring_validate_laws:return' => 'not-applicable',
    'lling_semiring_validate_laws:semiring' => 'non-null',
    'lling_semiring_validate_laws:weights' => 'nullable-if-count-is-zero',
    'lling_semiring_validate_laws:count' => 'not-applicable',
    'lling_semiring_validate_laws:epsilon' => 'not-applicable',
    'lling_lattice_open:return' => 'not-applicable',
    'lling_lattice_open:resource' => 'non-null',
    'lling_lattice_open:out_value' => 'non-null',
    'lling_lattice_free:return' => 'not-applicable',
    'lling_lattice_free:value' => 'nullable',
    'lling_lattice_domain_id:return' => 'not-applicable',
    'lling_lattice_domain_id:value' => 'non-null',
    'lling_lattice_domain_id:out_domain' => 'non-null',
    'lling_lattice_flags:return' => 'not-applicable',
    'lling_lattice_flags:value' => 'non-null',
    'lling_lattice_flags:out_flags' => 'non-null',
    'lling_lattice_join:return' => 'not-applicable',
    'lling_lattice_join:left' => 'non-null',
    'lling_lattice_join:right' => 'non-null',
    'lling_lattice_join:out_value' => 'non-null',
    'lling_lattice_meet:return' => 'not-applicable',
    'lling_lattice_meet:left' => 'non-null',
    'lling_lattice_meet:right' => 'non-null',
    'lling_lattice_meet:out_value' => 'non-null',
    'lling_lattice_equal:return' => 'not-applicable',
    'lling_lattice_equal:left' => 'non-null',
    'lling_lattice_equal:right' => 'non-null',
    'lling_lattice_equal:out_equal' => 'non-null',
    'lling_lattice_stable_bytes:return' => 'not-applicable',
    'lling_lattice_stable_bytes:value' => 'non-null',
    'lling_lattice_stable_bytes:out_bytes' => 'nullable-if-capacity-is-zero',
    'lling_lattice_stable_bytes:capacity' => 'not-applicable',
    'lling_lattice_stable_bytes:out_written' => 'non-null',
    'lling_lattice_stable_bytes:out_required' => 'non-null',
    'lling_lattice_diagnostic:return' => 'not-applicable',
    'lling_lattice_diagnostic:value' => 'non-null',
    'lling_lattice_diagnostic:out_bytes' => 'nullable-if-capacity-is-zero',
    'lling_lattice_diagnostic:capacity' => 'not-applicable',
    'lling_lattice_diagnostic:out_written' => 'non-null',
    'lling_lattice_diagnostic:out_required' => 'non-null',
    'lling_lattice_join_many:return' => 'not-applicable',
    'lling_lattice_join_many:receiver' => 'non-null',
    'lling_lattice_join_many:others' => 'nullable-if-count-is-zero',
    'lling_lattice_join_many:count' => 'not-applicable',
    'lling_lattice_join_many:out_value' => 'non-null',
    'lling_lattice_meet_many:return' => 'not-applicable',
    'lling_lattice_meet_many:receiver' => 'non-null',
    'lling_lattice_meet_many:others' => 'nullable-if-count-is-zero',
    'lling_lattice_meet_many:count' => 'not-applicable',
    'lling_lattice_meet_many:out_value' => 'non-null',
    'lling_lattice_validate_laws:return' => 'not-applicable',
    'lling_lattice_validate_laws:values' => 'nullable-if-count-is-zero',
    'lling_lattice_validate_laws:count' => 'not-applicable',
    'lling_wfst_builder_new:return' => 'not-applicable',
    'lling_wfst_builder_new:out_builder' => 'non-null',
    'lling_wfst_builder_free:return' => 'not-applicable',
    'lling_wfst_builder_free:builder' => 'nullable',
    'lling_wfst_builder_reserve_states:return' => 'not-applicable',
    'lling_wfst_builder_reserve_states:builder' => 'non-null',
    'lling_wfst_builder_reserve_states:additional' => 'not-applicable',
    'lling_wfst_builder_add_state:return' => 'not-applicable',
    'lling_wfst_builder_add_state:builder' => 'non-null',
    'lling_wfst_builder_add_state:out_state' => 'non-null',
    'lling_wfst_builder_set_start:return' => 'not-applicable',
    'lling_wfst_builder_set_start:builder' => 'non-null',
    'lling_wfst_builder_set_start:state' => 'not-applicable',
    'lling_wfst_builder_set_final:return' => 'not-applicable',
    'lling_wfst_builder_set_final:builder' => 'non-null',
    'lling_wfst_builder_set_final:state' => 'not-applicable',
    'lling_wfst_builder_set_final:weight' => 'not-applicable',
    'lling_wfst_builder_clear_final:return' => 'not-applicable',
    'lling_wfst_builder_clear_final:builder' => 'non-null',
    'lling_wfst_builder_clear_final:state' => 'not-applicable',
    'lling_wfst_builder_add_arc:return' => 'not-applicable',
    'lling_wfst_builder_add_arc:builder' => 'non-null',
    'lling_wfst_builder_add_arc:from' => 'not-applicable',
    'lling_wfst_builder_add_arc:input_label' => 'not-applicable',
    'lling_wfst_builder_add_arc:has_input' => 'not-applicable',
    'lling_wfst_builder_add_arc:output_label' => 'not-applicable',
    'lling_wfst_builder_add_arc:has_output' => 'not-applicable',
    'lling_wfst_builder_add_arc:to' => 'not-applicable',
    'lling_wfst_builder_add_arc:weight' => 'not-applicable',
    'lling_wfst_builder_build:return' => 'not-applicable',
    'lling_wfst_builder_build:builder' => 'non-null',
    'lling_wfst_builder_build:out_wfst' => 'non-null',
    'lling_wfst_free:return' => 'not-applicable',
    'lling_wfst_free:wfst' => 'nullable',
    'lling_wfst_import:return' => 'not-applicable',
    'lling_wfst_import:resource' => 'invalid-resource-rejected',
    'lling_wfst_import:out_wfst' => 'non-null',
    'lling_wfst_import_ref:return' => 'not-applicable',
    'lling_wfst_import_ref:resource' => 'non-null',
    'lling_wfst_import_ref:out_wfst' => 'non-null',
    'lling_wfst_compose:return' => 'not-applicable',
    'lling_wfst_compose:first' => 'invalid-resource-rejected',
    'lling_wfst_compose:second' => 'invalid-resource-rejected',
    'lling_wfst_compose:out_wfst' => 'non-null',
    'lling_wfst_compose_refs:return' => 'not-applicable',
    'lling_wfst_compose_refs:first' => 'non-null',
    'lling_wfst_compose_refs:second' => 'non-null',
    'lling_wfst_compose_refs:out_wfst' => 'non-null',
    'lling_wfst_resource:return' => 'not-applicable',
    'lling_wfst_resource:wfst' => 'non-null',
    'lling_wfst_resource:out_resource' => 'non-null',
    'lling_resource_release:return' => 'not-applicable',
    'lling_resource_release:resource' => 'invalid-resource-rejected',
    'lling_abi_v2_validate_header:return' => 'not-applicable',
    'lling_abi_v2_validate_header:header' => 'non-null',
    'lling_abi_v2_validate_header:required_size' => 'not-applicable',
    'lling_abi_v2_validate_header:known_flags' => 'not-applicable',
    'lling_abi_v2_validate_descriptor:return' => 'not-applicable',
    'lling_abi_v2_validate_descriptor:descriptor' => 'non-null',
    'lling_abi_v2_validate_descriptor:out_typed_evidence_allowed' => 'non-null',
    'lling_abi_v2_validate_budget:return' => 'not-applicable',
    'lling_abi_v2_validate_budget:budget' => 'non-null',
    'lling_abi_v2_validate_outcome:return' => 'not-applicable',
    'lling_abi_v2_validate_outcome:outcome' => 'non-null',
    'lling_abi_v2_validate_outcome:resource_present' => 'not-applicable',
    'lling_abi_v2_validate_outcome:evidence_present' => 'not-applicable',
    'lling_abi_v2_validate_outcome:out_authoritative_exact' => 'non-null',
    'lling_abi_v2_identity_matches:return' => 'not-applicable',
    'lling_abi_v2_identity_matches:expected' => 'non-null',
    'lling_abi_v2_identity_matches:observed' => 'non-null',
    'lling_abi_v2_identity_matches:out_matches' => 'non-null',
    'lling_cancellation_v2_new:return' => 'not-applicable',
    'lling_cancellation_v2_new:out_cancellation' => 'non-null',
    'lling_cancellation_v2_request:return' => 'not-applicable',
    'lling_cancellation_v2_request:cancellation' => 'non-null',
    'lling_cancellation_v2_request:reason' => 'not-applicable',
    'lling_cancellation_v2_reason:return' => 'not-applicable',
    'lling_cancellation_v2_reason:cancellation' => 'non-null',
    'lling_cancellation_v2_reason:out_reason' => 'non-null',
    'lling_cancellation_v2_free:return' => 'not-applicable',
    'lling_cancellation_v2_free:cancellation' => 'non-null',
    'lling_raku_provider_configure:return' => 'not-applicable',
    'lling_raku_provider_configure:drop' => 'non-null',
    'lling_raku_provider_configure:start' => 'non-null',
    'lling_raku_provider_configure:count' => 'non-null',
    'lling_raku_provider_configure:state_info' => 'non-null',
    'lling_raku_provider_configure:state_arcs' => 'non-null',
    'lling_raku_provider_create:return' => 'not-applicable',
    'lling_raku_provider_create:unit_domain' => 'not-applicable',
    'lling_raku_provider_create:weight_domain' => 'not-applicable',
    'lling_raku_provider_create:flags' => 'not-applicable',
    'lling_raku_provider_create:host_context' => 'non-null',
    'lling_raku_provider_create:out_resource' => 'non-null',
    'lling_raku_semiring_configure_lifecycle:return' => 'not-applicable',
    'lling_raku_semiring_configure_lifecycle:drop' => 'non-null',
    'lling_raku_semiring_configure_lifecycle:zero' => 'non-null',
    'lling_raku_semiring_configure_lifecycle:one' => 'non-null',
    'lling_raku_semiring_configure_lifecycle:clone_value' => 'non-null',
    'lling_raku_semiring_configure_lifecycle:release_values' => 'non-null',
    'lling_raku_semiring_configure_algebra:return' => 'not-applicable',
    'lling_raku_semiring_configure_algebra:plus' => 'non-null',
    'lling_raku_semiring_configure_algebra:times' => 'non-null',
    'lling_raku_semiring_configure_algebra:equal' => 'non-null',
    'lling_raku_semiring_configure_algebra:approx_equal' => 'non-null',
    'lling_raku_semiring_configure_algebra:natural_order' => 'non-null',
    'lling_raku_semiring_configure_buffers:return' => 'not-applicable',
    'lling_raku_semiring_configure_buffers:stable_bytes' => 'non-null',
    'lling_raku_semiring_configure_buffers:diagnostic' => 'non-null',
    'lling_raku_semiring_configure_buffers:plus_many' => 'non-null',
    'lling_raku_semiring_configure_buffers:times_many' => 'non-null',
    'lling_raku_semiring_configure_optional:return' => 'not-applicable',
    'lling_raku_semiring_configure_optional:divide' => 'non-null',
    'lling_raku_semiring_configure_optional:left_divide' => 'non-null',
    'lling_raku_semiring_configure_optional:star' => 'non-null',
    'lling_raku_semiring_configure_optional:numerical_value' => 'non-null',
    'lling_raku_semiring_configure_optional:to_probability' => 'non-null',
    'lling_raku_semiring_configure_metadata:return' => 'not-applicable',
    'lling_raku_semiring_configure_metadata:quantize' => 'non-null',
    'lling_raku_semiring_configure_metadata:closure_bound' => 'non-null',
    'lling_raku_semiring_create:return' => 'not-applicable',
    'lling_raku_semiring_create:flags' => 'not-applicable',
    'lling_raku_semiring_create:domain_id' => 'non-null',
    'lling_raku_semiring_create:properties' => 'not-applicable',
    'lling_raku_semiring_create:has_division' => 'not-applicable',
    'lling_raku_semiring_create:has_star' => 'not-applicable',
    'lling_raku_semiring_create:has_numeric' => 'not-applicable',
    'lling_raku_semiring_create:host_context' => 'non-null',
    'lling_raku_semiring_create:out_resource' => 'non-null',
);

our constant CALLBACK-OWNERSHIP is export(:metadata) = Map.new(
    'LlingRakuDrop:return' => 'none',
    'LlingRakuDrop:host_context' => 'borrowed-for-callback',
    'LlingRakuStart:return' => 'value',
    'LlingRakuStart:host_context' => 'borrowed-for-callback',
    'LlingRakuStart:out_state' => 'borrowed-output-slot',
    'LlingRakuCount:return' => 'value',
    'LlingRakuCount:host_context' => 'borrowed-for-callback',
    'LlingRakuCount:out_count' => 'borrowed-output-slot',
    'LlingRakuCount:out_known' => 'borrowed-output-slot',
    'LlingRakuStateInfo:return' => 'value',
    'LlingRakuStateInfo:host_context' => 'borrowed-for-callback',
    'LlingRakuStateInfo:state' => 'value',
    'LlingRakuStateInfo:out_valid' => 'borrowed-output-slot',
    'LlingRakuStateInfo:out_is_final' => 'borrowed-output-slot',
    'LlingRakuStateInfo:out_final_weight' => 'borrowed-output-slot',
    'LlingRakuStateArcs:return' => 'value',
    'LlingRakuStateArcs:host_context' => 'borrowed-for-callback',
    'LlingRakuStateArcs:state' => 'value',
    'LlingRakuStateArcs:start' => 'value',
    'LlingRakuStateArcs:out_arcs' => 'borrowed-output-buffer',
    'LlingRakuStateArcs:capacity' => 'value',
    'LlingRakuStateArcs:out_written' => 'borrowed-output-slot',
    'LlingRakuStateArcs:out_total' => 'borrowed-output-slot',
    'LlingRakuSemiringIdentity:return' => 'value',
    'LlingRakuSemiringIdentity:host_context' => 'borrowed-for-callback',
    'LlingRakuSemiringIdentity:out_value' => 'borrowed-output-slot',
    'LlingRakuSemiringClone:return' => 'value',
    'LlingRakuSemiringClone:host_context' => 'borrowed-for-callback',
    'LlingRakuSemiringClone:value' => 'borrowed-for-callback',
    'LlingRakuSemiringClone:out_value' => 'borrowed-output-slot',
    'LlingRakuSemiringRelease:return' => 'value',
    'LlingRakuSemiringRelease:host_context' => 'borrowed-for-callback',
    'LlingRakuSemiringRelease:values' => 'consumed-provider-token-array',
    'LlingRakuSemiringRelease:count' => 'value',
    'LlingRakuSemiringBinary:return' => 'value',
    'LlingRakuSemiringBinary:host_context' => 'borrowed-for-callback',
    'LlingRakuSemiringBinary:left' => 'borrowed-for-callback',
    'LlingRakuSemiringBinary:right' => 'borrowed-for-callback',
    'LlingRakuSemiringBinary:out_value' => 'borrowed-output-slot',
    'LlingRakuSemiringEqual:return' => 'value',
    'LlingRakuSemiringEqual:host_context' => 'borrowed-for-callback',
    'LlingRakuSemiringEqual:left' => 'borrowed-for-callback',
    'LlingRakuSemiringEqual:right' => 'borrowed-for-callback',
    'LlingRakuSemiringEqual:out_equal' => 'borrowed-output-slot',
    'LlingRakuSemiringApprox:return' => 'value',
    'LlingRakuSemiringApprox:host_context' => 'borrowed-for-callback',
    'LlingRakuSemiringApprox:left' => 'borrowed-for-callback',
    'LlingRakuSemiringApprox:right' => 'borrowed-for-callback',
    'LlingRakuSemiringApprox:epsilon' => 'value',
    'LlingRakuSemiringApprox:out_equal' => 'borrowed-output-slot',
    'LlingRakuSemiringOrder:return' => 'value',
    'LlingRakuSemiringOrder:host_context' => 'borrowed-for-callback',
    'LlingRakuSemiringOrder:left' => 'borrowed-for-callback',
    'LlingRakuSemiringOrder:right' => 'borrowed-for-callback',
    'LlingRakuSemiringOrder:out_order' => 'borrowed-output-slot',
    'LlingRakuSemiringBytes:return' => 'value',
    'LlingRakuSemiringBytes:host_context' => 'borrowed-for-callback',
    'LlingRakuSemiringBytes:value' => 'borrowed-for-callback',
    'LlingRakuSemiringBytes:out_bytes' => 'borrowed-output-buffer',
    'LlingRakuSemiringBytes:capacity' => 'value',
    'LlingRakuSemiringBytes:out_written' => 'borrowed-output-slot',
    'LlingRakuSemiringBytes:out_required' => 'borrowed-output-slot',
    'LlingRakuSemiringMany:return' => 'value',
    'LlingRakuSemiringMany:host_context' => 'borrowed-for-callback',
    'LlingRakuSemiringMany:values' => 'borrowed-array-for-callback',
    'LlingRakuSemiringMany:count' => 'value',
    'LlingRakuSemiringMany:out_value' => 'borrowed-output-slot',
    'LlingRakuSemiringUnary:return' => 'value',
    'LlingRakuSemiringUnary:host_context' => 'borrowed-for-callback',
    'LlingRakuSemiringUnary:value' => 'borrowed-for-callback',
    'LlingRakuSemiringUnary:out_value' => 'borrowed-output-slot',
    'LlingRakuSemiringNumerical:return' => 'value',
    'LlingRakuSemiringNumerical:host_context' => 'borrowed-for-callback',
    'LlingRakuSemiringNumerical:value' => 'borrowed-for-callback',
    'LlingRakuSemiringNumerical:out_value' => 'borrowed-output-slot',
    'LlingRakuSemiringQuantize:return' => 'value',
    'LlingRakuSemiringQuantize:host_context' => 'borrowed-for-callback',
    'LlingRakuSemiringQuantize:value' => 'borrowed-for-callback',
    'LlingRakuSemiringQuantize:epsilon' => 'value',
    'LlingRakuSemiringQuantize:out_value' => 'borrowed-output-slot',
    'LlingRakuSemiringClosure:return' => 'value',
    'LlingRakuSemiringClosure:host_context' => 'borrowed-for-callback',
    'LlingRakuSemiringClosure:out_bound' => 'borrowed-output-slot',
    'LlingRakuSemiringClosure:out_known' => 'borrowed-output-slot',
);

our constant CALLBACK-NULLABILITY is export(:metadata) = Map.new(
    'LlingRakuDrop:return' => 'not-applicable',
    'LlingRakuDrop:host_context' => 'non-null',
    'LlingRakuStart:return' => 'not-applicable',
    'LlingRakuStart:host_context' => 'non-null',
    'LlingRakuStart:out_state' => 'non-null',
    'LlingRakuCount:return' => 'not-applicable',
    'LlingRakuCount:host_context' => 'non-null',
    'LlingRakuCount:out_count' => 'non-null',
    'LlingRakuCount:out_known' => 'non-null',
    'LlingRakuStateInfo:return' => 'not-applicable',
    'LlingRakuStateInfo:host_context' => 'non-null',
    'LlingRakuStateInfo:state' => 'not-applicable',
    'LlingRakuStateInfo:out_valid' => 'non-null',
    'LlingRakuStateInfo:out_is_final' => 'non-null',
    'LlingRakuStateInfo:out_final_weight' => 'non-null',
    'LlingRakuStateArcs:return' => 'not-applicable',
    'LlingRakuStateArcs:host_context' => 'non-null',
    'LlingRakuStateArcs:state' => 'not-applicable',
    'LlingRakuStateArcs:start' => 'not-applicable',
    'LlingRakuStateArcs:out_arcs' => 'nullable-if-capacity-is-zero',
    'LlingRakuStateArcs:capacity' => 'not-applicable',
    'LlingRakuStateArcs:out_written' => 'non-null',
    'LlingRakuStateArcs:out_total' => 'non-null',
    'LlingRakuSemiringIdentity:return' => 'not-applicable',
    'LlingRakuSemiringIdentity:host_context' => 'non-null',
    'LlingRakuSemiringIdentity:out_value' => 'non-null',
    'LlingRakuSemiringClone:return' => 'not-applicable',
    'LlingRakuSemiringClone:host_context' => 'non-null',
    'LlingRakuSemiringClone:value' => 'non-null',
    'LlingRakuSemiringClone:out_value' => 'non-null',
    'LlingRakuSemiringRelease:return' => 'not-applicable',
    'LlingRakuSemiringRelease:host_context' => 'non-null',
    'LlingRakuSemiringRelease:values' => 'nullable-if-count-is-zero',
    'LlingRakuSemiringRelease:count' => 'not-applicable',
    'LlingRakuSemiringBinary:return' => 'not-applicable',
    'LlingRakuSemiringBinary:host_context' => 'non-null',
    'LlingRakuSemiringBinary:left' => 'non-null',
    'LlingRakuSemiringBinary:right' => 'non-null',
    'LlingRakuSemiringBinary:out_value' => 'non-null',
    'LlingRakuSemiringEqual:return' => 'not-applicable',
    'LlingRakuSemiringEqual:host_context' => 'non-null',
    'LlingRakuSemiringEqual:left' => 'non-null',
    'LlingRakuSemiringEqual:right' => 'non-null',
    'LlingRakuSemiringEqual:out_equal' => 'non-null',
    'LlingRakuSemiringApprox:return' => 'not-applicable',
    'LlingRakuSemiringApprox:host_context' => 'non-null',
    'LlingRakuSemiringApprox:left' => 'non-null',
    'LlingRakuSemiringApprox:right' => 'non-null',
    'LlingRakuSemiringApprox:epsilon' => 'not-applicable',
    'LlingRakuSemiringApprox:out_equal' => 'non-null',
    'LlingRakuSemiringOrder:return' => 'not-applicable',
    'LlingRakuSemiringOrder:host_context' => 'non-null',
    'LlingRakuSemiringOrder:left' => 'non-null',
    'LlingRakuSemiringOrder:right' => 'non-null',
    'LlingRakuSemiringOrder:out_order' => 'non-null',
    'LlingRakuSemiringBytes:return' => 'not-applicable',
    'LlingRakuSemiringBytes:host_context' => 'non-null',
    'LlingRakuSemiringBytes:value' => 'non-null',
    'LlingRakuSemiringBytes:out_bytes' => 'nullable-if-capacity-is-zero',
    'LlingRakuSemiringBytes:capacity' => 'not-applicable',
    'LlingRakuSemiringBytes:out_written' => 'non-null',
    'LlingRakuSemiringBytes:out_required' => 'non-null',
    'LlingRakuSemiringMany:return' => 'not-applicable',
    'LlingRakuSemiringMany:host_context' => 'non-null',
    'LlingRakuSemiringMany:values' => 'nullable-if-count-is-zero',
    'LlingRakuSemiringMany:count' => 'not-applicable',
    'LlingRakuSemiringMany:out_value' => 'non-null',
    'LlingRakuSemiringUnary:return' => 'not-applicable',
    'LlingRakuSemiringUnary:host_context' => 'non-null',
    'LlingRakuSemiringUnary:value' => 'non-null',
    'LlingRakuSemiringUnary:out_value' => 'non-null',
    'LlingRakuSemiringNumerical:return' => 'not-applicable',
    'LlingRakuSemiringNumerical:host_context' => 'non-null',
    'LlingRakuSemiringNumerical:value' => 'non-null',
    'LlingRakuSemiringNumerical:out_value' => 'non-null',
    'LlingRakuSemiringQuantize:return' => 'not-applicable',
    'LlingRakuSemiringQuantize:host_context' => 'non-null',
    'LlingRakuSemiringQuantize:value' => 'non-null',
    'LlingRakuSemiringQuantize:epsilon' => 'not-applicable',
    'LlingRakuSemiringQuantize:out_value' => 'non-null',
    'LlingRakuSemiringClosure:return' => 'not-applicable',
    'LlingRakuSemiringClosure:host_context' => 'non-null',
    'LlingRakuSemiringClosure:out_bound' => 'non-null',
    'LlingRakuSemiringClosure:out_known' => 'non-null',
);

our constant RAKU-BINDING-EXCLUSIONS is export(:metadata) = Map.new(
    'lling_wfst_import' => 'NativeCall does not portably pass the imported VtResource C aggregate by value; use the pointer-form API or the interop resource owner',
    'lling_wfst_compose' => 'NativeCall does not portably pass the imported VtResource C aggregate by value; use the pointer-form API or the interop resource owner',
    'lling_resource_release' => 'NativeCall does not portably pass the imported VtResource C aggregate by value; use the pointer-form API or the interop resource owner',
);

sub native-library(--> Str:D) {
    return %*ENV<LLING_LLANG_LIBRARY> if %*ENV<LLING_LLANG_LIBRARY>:exists;
    $*DISTRO.is-win ?? 'lling_llang.dll' !!
        $*KERNEL.name eq 'darwin' ?? 'liblling_llang.dylib' !!
        'liblling_llang.so'
}

sub provider-library(--> Str:D) {
    return %*ENV<LLING_LLANG_RAKU_PROVIDER_LIB> if %*ENV<LLING_LLANG_RAKU_PROVIDER_LIB>:exists;
    return %?RESOURCES<libraries/lling_llang_raku_provider>.IO.Str
        if %?RESOURCES<libraries/lling_llang_raku_provider>:exists;
    $*DISTRO.is-win ?? 'lling_llang_raku_provider.dll' !!
        $*KERNEL.name eq 'darwin' ?? 'liblling_llang_raku_provider.dylib' !!
        'liblling_llang_raku_provider.so'
}

our sub lling-abi-version(
    --> uint32
)
    is native(&native-library)
    is symbol('lling_abi_version')
    is export(:native)
{ * }

our sub lling-api-revision(
    --> uint32
)
    is native(&native-library)
    is symbol('lling_llang_api_revision')
    is export(:native)
{ * }

our sub lling-last-error-message(
    --> Str
)
    is native(&native-library)
    is symbol('lling_last_error_message')
    is export(:native)
{ * }

our sub lling-semiring-open(
    Vinary::Tree::Interop::RawResource,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_open')
    is export(:native)
{ * }

our sub lling-semiring-free(
    Pointer
)
    is native(&native-library)
    is symbol('lling_semiring_free')
    is export(:native)
{ * }

our sub lling-semiring-weight-free(
    Pointer
)
    is native(&native-library)
    is symbol('lling_semiring_weight_free')
    is export(:native)
{ * }

our sub lling-semiring-properties(
    Pointer,
    uint64 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_properties')
    is export(:native)
{ * }

our sub lling-semiring-zero(
    Pointer,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_zero')
    is export(:native)
{ * }

our sub lling-semiring-one(
    Pointer,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_one')
    is export(:native)
{ * }

our sub lling-semiring-weight-clone(
    Pointer,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_weight_clone')
    is export(:native)
{ * }

our sub lling-semiring-plus(
    Pointer,
    Pointer,
    Pointer,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_plus')
    is export(:native)
{ * }

our sub lling-semiring-times(
    Pointer,
    Pointer,
    Pointer,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_times')
    is export(:native)
{ * }

our sub lling-semiring-equal(
    Pointer,
    Pointer,
    Pointer,
    uint8 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_equal')
    is export(:native)
{ * }

our sub lling-semiring-approx-equal(
    Pointer,
    Pointer,
    Pointer,
    num64,
    uint8 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_approx_equal')
    is export(:native)
{ * }

our sub lling-semiring-natural-order(
    Pointer,
    Pointer,
    Pointer,
    int32 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_natural_order')
    is export(:native)
{ * }

our sub lling-semiring-divide(
    Pointer,
    Pointer,
    Pointer,
    Pointer is rw,
    uint8 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_divide')
    is export(:native)
{ * }

our sub lling-semiring-left-divide(
    Pointer,
    Pointer,
    Pointer,
    Pointer is rw,
    uint8 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_left_divide')
    is export(:native)
{ * }

our sub lling-semiring-star(
    Pointer,
    Pointer,
    Pointer is rw,
    uint8 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_star')
    is export(:native)
{ * }

our sub lling-semiring-numerical-value(
    Pointer,
    Pointer,
    num64 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_numerical_value')
    is export(:native)
{ * }

our sub lling-semiring-quantize(
    Pointer,
    Pointer,
    num64,
    int64 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_quantize')
    is export(:native)
{ * }

our sub lling-semiring-to-probability(
    Pointer,
    Pointer,
    num64 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_to_probability')
    is export(:native)
{ * }

our sub lling-semiring-closure-bound(
    Pointer,
    size_t is rw,
    uint8 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_closure_bound')
    is export(:native)
{ * }

our sub lling-semiring-stable-bytes(
    Pointer,
    Pointer,
    Pointer,
    size_t,
    size_t is rw,
    size_t is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_stable_bytes')
    is export(:native)
{ * }

our sub lling-semiring-diagnostic(
    Pointer,
    Pointer,
    Pointer,
    size_t,
    size_t is rw,
    size_t is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_diagnostic')
    is export(:native)
{ * }

our sub lling-semiring-plus-many(
    Pointer,
    Pointer,
    size_t,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_plus_many')
    is export(:native)
{ * }

our sub lling-semiring-times-many(
    Pointer,
    Pointer,
    size_t,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_times_many')
    is export(:native)
{ * }

our sub lling-semiring-validate-laws(
    Pointer,
    Pointer,
    size_t,
    num64,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_semiring_validate_laws')
    is export(:native)
{ * }

our sub lling-lattice-open(
    Vinary::Tree::Interop::RawResource,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_lattice_open')
    is export(:native)
{ * }

our sub lling-lattice-free(
    Pointer
)
    is native(&native-library)
    is symbol('lling_lattice_free')
    is export(:native)
{ * }

our sub lling-lattice-domain-id(
    Pointer,
    Vinary::Tree::Interop::InterfaceId,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_lattice_domain_id')
    is export(:native)
{ * }

our sub lling-lattice-flags(
    Pointer,
    uint64 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_lattice_flags')
    is export(:native)
{ * }

our sub lling-lattice-join(
    Pointer,
    Pointer,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_lattice_join')
    is export(:native)
{ * }

our sub lling-lattice-meet(
    Pointer,
    Pointer,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_lattice_meet')
    is export(:native)
{ * }

our sub lling-lattice-equal(
    Pointer,
    Pointer,
    uint8 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_lattice_equal')
    is export(:native)
{ * }

our sub lling-lattice-stable-bytes(
    Pointer,
    Pointer,
    size_t,
    size_t is rw,
    size_t is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_lattice_stable_bytes')
    is export(:native)
{ * }

our sub lling-lattice-diagnostic(
    Pointer,
    Pointer,
    size_t,
    size_t is rw,
    size_t is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_lattice_diagnostic')
    is export(:native)
{ * }

our sub lling-lattice-join-many(
    Pointer,
    Pointer,
    size_t,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_lattice_join_many')
    is export(:native)
{ * }

our sub lling-lattice-meet-many(
    Pointer,
    Pointer,
    size_t,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_lattice_meet_many')
    is export(:native)
{ * }

our sub lling-lattice-validate-laws(
    Pointer,
    size_t,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_lattice_validate_laws')
    is export(:native)
{ * }

our sub lling-wfst-builder-new(
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_wfst_builder_new')
    is export(:native)
{ * }

our sub lling-wfst-builder-free(
    Pointer
)
    is native(&native-library)
    is symbol('lling_wfst_builder_free')
    is export(:native)
{ * }

our sub lling-wfst-builder-reserve-states(
    Pointer,
    size_t,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_wfst_builder_reserve_states')
    is export(:native)
{ * }

our sub lling-wfst-builder-add-state(
    Pointer,
    uint32 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_wfst_builder_add_state')
    is export(:native)
{ * }

our sub lling-wfst-builder-set-start(
    Pointer,
    uint32,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_wfst_builder_set_start')
    is export(:native)
{ * }

our sub lling-wfst-builder-set-final(
    Pointer,
    uint32,
    num64,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_wfst_builder_set_final')
    is export(:native)
{ * }

our sub lling-wfst-builder-clear-final(
    Pointer,
    uint32,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_wfst_builder_clear_final')
    is export(:native)
{ * }

our sub lling-wfst-builder-add-arc(
    Pointer,
    uint32,
    uint64,
    uint8,
    uint64,
    uint8,
    uint32,
    num64,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_wfst_builder_add_arc')
    is export(:native)
{ * }

our sub lling-wfst-builder-build(
    Pointer,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_wfst_builder_build')
    is export(:native)
{ * }

our sub lling-wfst-free(
    Pointer
)
    is native(&native-library)
    is symbol('lling_wfst_free')
    is export(:native)
{ * }

our sub lling-wfst-import-ref(
    Vinary::Tree::Interop::RawResource,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_wfst_import_ref')
    is export(:native)
{ * }

our sub lling-wfst-compose-refs(
    Vinary::Tree::Interop::RawResource,
    Vinary::Tree::Interop::RawResource,
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_wfst_compose_refs')
    is export(:native)
{ * }

our sub lling-wfst-resource(
    Pointer,
    Vinary::Tree::Interop::RawResource,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_wfst_resource')
    is export(:native)
{ * }

our sub lling-abi-v2-validate-header(
    Pointer,
    uint32,
    uint64,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_abi_v2_validate_header')
    is export(:native)
{ * }

our sub lling-abi-v2-validate-descriptor(
    Pointer,
    uint8 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_abi_v2_validate_descriptor')
    is export(:native)
{ * }

our sub lling-abi-v2-validate-budget(
    Pointer,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_abi_v2_validate_budget')
    is export(:native)
{ * }

our sub lling-abi-v2-validate-outcome(
    Pointer,
    uint8,
    uint8,
    uint8 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_abi_v2_validate_outcome')
    is export(:native)
{ * }

our sub lling-abi-v2-identity-matches(
    Pointer,
    Pointer,
    uint8 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_abi_v2_identity_matches')
    is export(:native)
{ * }

our sub lling-cancellation-v2-new(
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_cancellation_v2_new')
    is export(:native)
{ * }

our sub lling-cancellation-v2-request(
    Pointer,
    uint32,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_cancellation_v2_request')
    is export(:native)
{ * }

our sub lling-cancellation-v2-reason(
    Pointer,
    uint32 is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_cancellation_v2_reason')
    is export(:native)
{ * }

our sub lling-cancellation-v2-free(
    Pointer is rw,
    --> uint32
)
    is native(&native-library)
    is symbol('lling_cancellation_v2_free')
    is export(:native)
{ * }

our sub configure-provider(
    &drop (Pointer),
    &start (Pointer, Pointer --> int32),
    &count (Pointer, Pointer, Pointer --> int32),
    &state-info (Pointer, uint64, Pointer, Pointer, Pointer --> int32),
    &state-arcs (Pointer, uint64, size_t, Pointer, size_t, Pointer, Pointer --> int32),
    --> int32
)
    is native(&provider-library)
    is symbol('lling_raku_provider_configure')
    is export(:native)
{ * }

our sub create-provider(
    uint32,
    uint32,
    uint64,
    Pointer,
    Vinary::Tree::Interop::RawResource,
    --> int32
)
    is native(&provider-library)
    is symbol('lling_raku_provider_create')
    is export(:native)
{ * }

our sub configure-semiring-lifecycle(
    &drop (Pointer),
    &zero (Pointer, Pointer --> int32),
    &one (Pointer, Pointer --> int32),
    &clone-value (Pointer, Pointer, Pointer --> int32),
    &release-values (Pointer, Pointer, size_t --> int32),
    --> int32
)
    is native(&provider-library)
    is symbol('lling_raku_semiring_configure_lifecycle')
    is export(:native)
{ * }

our sub configure-semiring-algebra(
    &plus (Pointer, Pointer, Pointer, Pointer --> int32),
    &times (Pointer, Pointer, Pointer, Pointer --> int32),
    &equal (Pointer, Pointer, Pointer, Pointer --> int32),
    &approx-equal (Pointer, Pointer, Pointer, num64, Pointer --> int32),
    &natural-order (Pointer, Pointer, Pointer, Pointer --> int32),
    --> int32
)
    is native(&provider-library)
    is symbol('lling_raku_semiring_configure_algebra')
    is export(:native)
{ * }

our sub configure-semiring-buffers(
    &stable-bytes (Pointer, Pointer, Pointer, size_t, Pointer, Pointer --> int32),
    &diagnostic (Pointer, Pointer, Pointer, size_t, Pointer, Pointer --> int32),
    &plus-many (Pointer, Pointer, size_t, Pointer --> int32),
    &times-many (Pointer, Pointer, size_t, Pointer --> int32),
    --> int32
)
    is native(&provider-library)
    is symbol('lling_raku_semiring_configure_buffers')
    is export(:native)
{ * }

our sub configure-semiring-optional(
    &divide (Pointer, Pointer, Pointer, Pointer --> int32),
    &left-divide (Pointer, Pointer, Pointer, Pointer --> int32),
    &star (Pointer, Pointer, Pointer --> int32),
    &numerical-value (Pointer, Pointer, Pointer --> int32),
    &to-probability (Pointer, Pointer, Pointer --> int32),
    --> int32
)
    is native(&provider-library)
    is symbol('lling_raku_semiring_configure_optional')
    is export(:native)
{ * }

our sub configure-semiring-metadata(
    &quantize (Pointer, Pointer, num64, Pointer --> int32),
    &closure-bound (Pointer, Pointer, Pointer --> int32),
    --> int32
)
    is native(&provider-library)
    is symbol('lling_raku_semiring_configure_metadata')
    is export(:native)
{ * }

our sub create-semiring-provider(
    uint64,
    Vinary::Tree::Interop::InterfaceId,
    uint64,
    uint8,
    uint8,
    uint8,
    Pointer,
    Vinary::Tree::Interop::RawResource,
    --> int32
)
    is native(&provider-library)
    is symbol('lling_raku_semiring_create')
    is export(:native)
{ * }
