# Generated by scripts/generate-julia-path-properties.py; do not edit.
# Each testset maps one TLA invariant to actual Julia path API calls.
@testset "generated Julia path contract properties" begin
    @testset "TypeOK" begin
        for seed in 0:15
            check_julia_path_property(:type_ok, seed)
        end
    end
    @testset "GraphPinned" begin
        for seed in 0:15
            check_julia_path_property(:graph_pinned, seed)
        end
    end
    @testset "WorkBounded" begin
        for seed in 0:15
            check_julia_path_property(:work_bounded, seed)
        end
    end
    @testset "OutputBounded" begin
        for seed in 0:15
            check_julia_path_property(:output_bounded, seed)
        end
    end
    @testset "RankedOrder" begin
        for seed in 0:15
            check_julia_path_property(:ranked_order, seed)
        end
    end
    @testset "PruneSound" begin
        for seed in 0:15
            check_julia_path_property(:prune_sound, seed)
        end
    end
    @testset "SeedStable" begin
        for seed in 0:15
            check_julia_path_property(:seed_stable, seed)
        end
    end
    @testset "TerminalDistinct" begin
        for seed in 0:15
            check_julia_path_property(:terminal_distinct, seed)
        end
    end
    @testset "CancelSticky" begin
        for seed in 0:15
            check_julia_path_property(:cancel_sticky, seed)
        end
    end
    @testset "NumericFailureNoOutput" begin
        for seed in 0:15
            check_julia_path_property(:numeric_failure_no_output, seed)
        end
    end
    @testset "ReducerSettles" begin
        for seed in 0:15
            check_julia_path_property(:reducer_settles, seed)
        end
    end
end
