name = "LlingLlang"
uuid = "c0d6310b-ae37-4a72-96a5-37e0f0aef4be"
authors = ["Dylon Edwards <dylon.devo@gmail.com>"]
version = "4.0.0-rc.5"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
VinaryTreeInterop = "8d6503e5-4d65-4bd8-a8ee-293a0149584e"

[compat]
VinaryTreeInterop = "4"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
