#!/usr/bin/env python3
"""Extract each Julia path TLA invariant into bounded API property cases."""

import argparse
import difflib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / "proofs/doc/julia-path-invariants.json"
OUTPUT = ROOT / "bindings/julia/LlingLlang/test/generated_path_properties.jl"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    ledger = json.loads(LEDGER.read_text())
    model = (ROOT / ledger["model"]).read_text()
    rows = ledger["invariants"]
    names = [row["name"] for row in rows]
    properties = [row["property"] for row in rows]
    if len(names) != len(set(names)) or len(properties) != len(set(properties)):
        raise SystemExit("duplicate formal invariant or Julia property")
    if len(names) != 11:
        raise SystemExit("expected eleven Julia path invariants")
    suffix = model.split("Spec == Init /\\ [][Next]_vars", 1)
    if len(suffix) != 2:
        raise SystemExit("Julia path specification boundary changed")
    declared = re.findall(r"^([A-Za-z][A-Za-z0-9]*) ==", suffix[1], re.MULTILINE)
    if declared != names:
        raise SystemExit(f"invariant ledger differs from model: {declared!r}")
    for name in names:
        if re.search(rf"^{re.escape(name)} ==", model, re.MULTILINE) is None:
            raise SystemExit(f"missing model invariant: {name}")
    seeds = ledger["seed_count"]
    if not isinstance(seeds, int) or not 1 <= seeds <= 256:
        raise SystemExit("seed_count must be in 1..256")
    lines = [
        "# Generated by scripts/generate-julia-path-properties.py; do not edit.",
        "# Each testset maps one TLA invariant to actual Julia path API calls.",
        "@testset \"generated Julia path contract properties\" begin",
    ]
    for name, prop in zip(names, properties, strict=True):
        lines.extend([
            f'    @testset "{name}" begin',
            f"        for seed in 0:{seeds - 1}",
            f"            check_julia_path_property(:{prop}, seed)",
            "        end",
            "    end",
        ])
    lines.extend(["end", ""])
    expected = "\n".join(lines)
    if args.check:
        actual = OUTPUT.read_text() if OUTPUT.exists() else ""
        if actual != expected:
            raise SystemExit("".join(difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=str(OUTPUT), tofile="generated expected",
            )) or "generated Julia path properties are stale")
    else:
        OUTPUT.write_text(expected)


if __name__ == "__main__":
    main()
